# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_edit_interactive.ipynb.

# %% auto #0
__all__ = ['EDIT_INTERACTIVE_SYSTEM', 'CONTEXT_SESSION_SYSTEM', 'capture_call_text', 'notebook_view', 'notebooks_view',
           'ManagedContextMessage', 'managed_notebook_context', 'render_managed_context', 'EditSession',
           'find_context_command', 'apply_context_command', 'run_chat_with_context_commands', 'make_edit_tools',
           'make_context_tools', 'make_chat', 'run_context_session', 'response_text', 'plan_result_text', 'final_diff',
           'final_diffs', 'execute_plan', 'execute_project_plan']

# %% ../nbs/08_edit_interactive.ipynb #c7e88003
import ast
import inspect
import json
import os
import re
import signal
import traceback
from contextlib import contextmanager, redirect_stderr, redirect_stdout
from dataclasses import dataclass, field
from io import StringIO
from pathlib import Path
from threading import Lock, current_thread, main_thread
from fastcore.nbio import read_nb
from .edit import NotebookEditor
from .foundation import cap_text, cell_source, chapter_spans, commit_notebook, parse_one_cell
from .graph import symbol_usage_summary
from .knowledge import reference_query
from .parallel import notebook_locks
from .review import diff_nb

_CAPTURE_LOCK = Lock()

_AGENT_MAX_STEPS = 20
_AGENT_MAX_CONTEXT_STEPS = 5
_AGENT_MAX_CONTEXT_COMMANDS = 20
_AGENT_MAX_TIMEOUT_SECONDS = 120
_AGENT_MAX_MESSAGE_CHARS = 12000
_AGENT_MAX_NOTEBOOK_VIEW_CHARS = 80000
_AGENT_MAX_CELL_SOURCE_CHARS = 8000
_AGENT_MAX_LOG_ITEMS = 200
_AGENT_MAX_DIFF_CHARS = 50000


def _bounded_int(value, default, minimum, maximum, name):
    if value is None: value = default
    try:
        value = int(value)
    except (TypeError, ValueError):
        raise ValueError(f"{name} must be an integer") from None
    if value < minimum:
        raise ValueError(f"{name} must be >= {minimum}")
    return min(value, maximum)


def _bounded_text(text, limit=_AGENT_MAX_MESSAGE_CHARS):
    return cap_text(str(text or ""), limit)


def _bounded_items(items, limit=_AGENT_MAX_LOG_ITEMS):
    return list(items)[-limit:]

# %% ../nbs/08_edit_interactive.ipynb #0b709792
def _save_notebook(nb, path):
    return commit_notebook(path, nb, before=read_nb(path))

# %% ../nbs/08_edit_interactive.ipynb #57c2fd65
EDIT_INTERACTIVE_SYSTEM = """You are an nbskill notebook-editing subagent.
You may edit one or more target notebooks in one repository. You receive the
project description, a focused knowledge summary, optional caller/callee impact
for the symbols in scope, and a managed notebook context prepared by a separate
context-management step. There is no project-scope lookup tool because that
scope is injected into this prompt.

Use only the provided editing tools: str_replace, edit_cell, add_cell,
delete_cell, run_code, inspect_state, execute_cell, and query_knowledge. The
context-management tools are not available in this edit step. When more than one
notebook is in scope, pass the notebook path/name to edit and execution tools so
the target is explicit. Keep the work scoped to one small specific task.

For new behavior, use this loop:
1. Scratch: run the smallest experiment with run_code in the live notebook
   scope. Use budget_secs for code that might run long.
2. Inspect: use inspect_state to look at variables and functions before treating
   an experiment as correct.
3. Function: turn the working scratch into a focused function. Add a Markdown
   cell directly above exported code explaining why the function is needed.
4. Example: add an example cell directly below the function showing how it
   works. If the example is slow or produces artifacts, add `#| eval: false`.
5. Test: add a focused test cell directly below the example so future changes
   keep the same output.
6. Execute: use execute_cell to replay through the example or test. Pass
   rerun_all=True when earlier cells changed and the whole notebook state must
   be rebuilt.
7. Clean context: after scratch is stabilized into notebook cells, let the final
   context step fold or delete no-longer-needed working context.

Exceptions are returned to you as tool output; inspect them, edit, and execute
again. Stop as soon as the requested notebook change is complete. Your final
message must summarize what changed, what was executed, and what could not be
completed.
"""

CONTEXT_SESSION_SYSTEM = """You manage the context for an nbskill editing run.
You do not edit notebooks. Use only the context tools to open, fold, delete, or
edit managed context messages so the next editing step sees the smallest useful
context. Open the few chapters directly relevant to the plan, fold full chapters
to concise summaries after they are no longer useful, delete irrelevant material
from the active context while preserving the audit log, and leave the index
visible. Stop once the context is prepared or cleaned.
"""

# %% ../nbs/08_edit_interactive.ipynb #155505b9
def capture_call_text(func, **kwargs):
    "Run `func` and return captured stdout/stderr, or the return value."
    out, err = StringIO(), StringIO()
    with _CAPTURE_LOCK, redirect_stdout(out), redirect_stderr(err):
        result = func(**kwargs)
    chunks = []
    if out.getvalue(): chunks.append(out.getvalue().rstrip())
    if err.getvalue(): chunks.append(err.getvalue().rstrip())
    if result is not None and not chunks: chunks.append(str(result))
    return cap_text("\n".join(chunk for chunk in chunks if chunk), _AGENT_MAX_MESSAGE_CHARS)

# %% ../nbs/08_edit_interactive.ipynb #f2cd36c3
def notebook_view(path, revision=0):
    "Render one notebook as a compact, stable text view."
    path = Path(path)
    with notebook_locks(path):
        nb = read_nb(path)
        lines = [f"Notebook: {path}", f"Revision: {revision}", ""]
        for idx, cell in enumerate(nb.cells):
            lines.append(f"CELL {idx} id={cell.id} type={cell.cell_type}")
            lines.append("<<<SOURCE")
            lines.append(cap_text(cell_source(cell).rstrip(), _AGENT_MAX_CELL_SOURCE_CHARS))
            lines.append("SOURCE")
            lines.append("")
        return cap_text("\n".join(lines).rstrip() + "\n", _AGENT_MAX_NOTEBOOK_VIEW_CHARS)


def _split_notebooks(notebooks):
    if notebooks is None: return []
    if isinstance(notebooks, (str, Path)): return [item.strip() for item in str(notebooks).split(",") if item.strip()]
    return [str(item) for item in notebooks if str(item).strip()]


def _target_paths(notebooks):
    paths = [Path(item) for item in _split_notebooks(notebooks)]
    if not paths: raise ValueError("At least one target notebook is required.")
    seen, duplicates = set(), []
    for path in paths:
        key = path.as_posix()
        if key in seen: duplicates.append(key)
        seen.add(key)
    if duplicates: raise ValueError(f"Duplicate notebook target(s): {', '.join(sorted(duplicates))}")
    return paths


def _target_slug(path):
    rel = Path(path).with_suffix("").as_posix()
    return re.sub(r"[^A-Za-z0-9_.-]+", "-", rel).strip("-.") or "notebook"


def _target_label(paths):
    paths = [Path(path) for path in paths]
    if len(paths) == 1: return str(paths[0])
    return ", ".join(str(path) for path in paths)


def _resolve_target_path(paths, notebook=None):
    paths = [Path(path) for path in paths]
    name = _none_if_blank(notebook)
    if name is None:
        if len(paths) == 1: return paths[0]
        raise ValueError("notebook is required when an edit session has multiple target notebooks")
    matches = []
    for path in paths:
        choices = {str(path), path.as_posix(), path.name, path.stem, _target_slug(path)}
        if str(name) in choices: matches.append(path)
    if len(matches) == 1: return matches[0]
    if not matches: raise ValueError(f"Unknown target notebook {name!r}; choose one of: {_target_label(paths)}")
    raise ValueError(f"Ambiguous target notebook {name!r}")


def notebooks_view(paths, revision=0):
    "Render one or more notebooks as compact stable text."
    return "\n".join(notebook_view(path, revision=revision).rstrip() for path in _target_paths(paths)) + "\n"

# %% ../nbs/08_edit_interactive.ipynb #8b698a18
class ManagedContextMessage:
    "One mutable context message controlled by a stable tag."
    def __init__(self, tag, purpose, content, visible=True, removed=False, summary=""):
        self.tag = str(tag)
        self.purpose = str(purpose)
        self.content = str(content)
        self.visible = bool(visible)
        self.removed = bool(removed)
        self.summary = str(summary or "")


def _context_msg_get(msg, key):
    return msg.get(key) if isinstance(msg, dict) else getattr(msg, key)


def _context_msg_set(msg, key, value):
    if isinstance(msg, dict): msg[key] = value
    else: setattr(msg, key, value)


def _chapter_tag(cell, path=None):
    base = f"chapter:{getattr(cell, 'id', '')}"
    return base if path is None else f"notebook:{_target_slug(path)}:{base}"


def _public_symbols_in_source(source):
    try: tree = ast.parse(source)
    except SyntaxError: return []
    symbols = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) and not node.name.startswith("_"):
            symbols.append(node.name)
    return symbols


def _chapter_public_symbols(cells):
    symbols = []
    for cell in cells:
        if getattr(cell, "cell_type", None) == "code": symbols.extend(_public_symbols_in_source(cell_source(cell)))
    return symbols


def _first_markdown_paragraph(cells):
    for cell in cells:
        if getattr(cell, "cell_type", None) != "markdown": continue
        chunks, current = [], []
        for line in cell_source(cell).splitlines():
            stripped = line.strip()
            if stripped.startswith("#") or stripped.startswith("#|"): continue
            if stripped: current.append(stripped)
            elif current:
                chunks.append(" ".join(current))
                current = []
        if current: chunks.append(" ".join(current))
        if chunks: return cap_text(chunks[0], 360)
    return "No prose summary found."


def _chapter_summary(title, cells):
    symbols = _chapter_public_symbols(cells)
    parts = [f"{title}: {_first_markdown_paragraph(cells)}", f"cells={len(cells)}"]
    if symbols: parts.append("symbols=" + ", ".join(symbols[:8]))
    return " | ".join(parts)


def _chapter_source_view(path, span, cells):
    lines = [f"Full chapter context: {path}", f"Title: {span['title']}", f"Cells: {span['start']}:{span['end']}", ""]
    for idx in range(span["start"], span["end"]):
        cell = cells[idx]
        lines.append(f"CELL {idx} id={cell.id} type={cell.cell_type}")
        lines.append("<<<SOURCE")
        lines.append(cap_text(cell_source(cell).rstrip(), _AGENT_MAX_CELL_SOURCE_CHARS))
        lines.append("SOURCE")
        lines.append("")
    return cap_text("\n".join(lines).rstrip() + "\n", _AGENT_MAX_NOTEBOOK_VIEW_CHARS)


def managed_notebook_context(path, revision=0, previous=None):
    "Build mutable summary-first context messages for one or more target notebooks."
    paths = _target_paths(path)
    multi = len(paths) > 1
    old = {msg.tag: msg for msg in (previous or [])}
    index_lines = [
        "Managed notebook context",
        "Notebooks: " + _target_label(paths),
        f"Revision: {revision}",
        "",
        "Open messages render full content; folded messages render summaries; deleted messages are omitted.",
        "",
        "Chapter index:",
    ]
    messages = []
    for path in paths:
        with notebook_locks(path):
            nb = read_nb(path)
            spans = chapter_spans(nb.cells, levels=range(1, 7), fallback="Notebook")
            if multi:
                index_lines.append("")
                index_lines.append(f"Notebook: {path}")
            for span in spans:
                cells = list(nb.cells[span["start"]:span["end"]])
                tag = _chapter_tag(nb.cells[span["start"]], path if multi else None)
                summary = _chapter_summary(span["title"], cells)
                index_lines.append(f"- {tag} title={span['title']!r} cells={span['start']}:{span['end']} summary={summary}")
                messages.append(ManagedContextMessage(
                    tag=tag,
                    purpose=f"full chapter: {path} :: {span['title']}",
                    content=_chapter_source_view(path, span, nb.cells),
                    visible=False,
                    summary=summary,
                ))
    index = ManagedContextMessage(
        "notebook:index", "chapter summary index", "\n".join(index_lines).rstrip() + "\n",
        summary="Index of available notebook context messages.",
    )
    rebuilt = [index, *messages]
    for msg in rebuilt:
        prior = old.get(msg.tag)
        if prior is None: continue
        prior_summary = getattr(prior, "summary", "")
        if msg.tag != "notebook:index":
            msg.visible, msg.removed = prior.visible, prior.removed
            if prior_summary: msg.summary = prior_summary
        if prior.purpose.startswith("edited "):
            msg.purpose, msg.content = prior.purpose, prior.content
            if prior_summary: msg.summary = prior_summary
    return rebuilt


def render_managed_context(messages):
    "Render active managed context messages as a budgeted projection."
    visible = [msg for msg in messages if msg.visible and not msg.removed]
    folded = [msg for msg in messages if not msg.visible and not msg.removed]
    lines = ["Self-managed context messages", ""]
    for msg in visible:
        lines.append(f"<message tag={msg.tag!r} purpose={msg.purpose!r}>")
        lines.append(msg.content.rstrip())
        lines.append("</message>")
        lines.append("")
    if folded:
        lines.append("Folded messages:")
        for msg in folded:
            summary = (msg.summary or msg.purpose).rstrip()
            lines.append(f"<folded-message tag={msg.tag!r} purpose={msg.purpose!r}>")
            lines.append(summary)
            lines.append("</folded-message>")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"

# %% ../nbs/08_edit_interactive.ipynb #ab5864d9
@dataclass
class EditSession:
    "Mutable state for one edit-interactive notebook run."
    path: Path | str | list
    target_paths: list[Path] = field(default_factory=list)
    timeout: int = 30
    revision: int = 0
    agent_id: str | None = None
    log_path: Path | None = None
    log: list[str] = field(default_factory=list)
    tool_log: list[str] = field(default_factory=list)
    history: list[dict] = field(default_factory=list)
    messages: list[dict] = field(default_factory=list)
    managed_context: list[ManagedContextMessage] = field(default_factory=list)
    context_command_log: list[dict] = field(default_factory=list)
    live_ns: dict = field(default_factory=lambda: {"__name__": "__main__"})
    live_ns_by_path: dict = field(default_factory=dict)
    executed_until_idx: int = -1
    executed_until_by_path: dict = field(default_factory=dict)
    chat: object | None = None
    notebook_msg_idx: int | None = None
    context_msg_idx: int | None = None
    def __post_init__(self):
        paths = self.target_paths or _target_paths(self.path)
        self.target_paths = [Path(path) for path in paths]
        self.path = self.target_paths[0]
        if self.agent_id is None: self.agent_id = _agent_notebook_id(_target_label(self.target_paths))
        if self.log_path is None: self.log_path = Path("log") / f"agent-{self.agent_id}.log"
    def target_path(self, notebook=None):
        "Resolve a user-facing notebook selector against this session."
        return _resolve_target_path(self.target_paths, notebook)
    def _state_key(self, path):
        return Path(path).as_posix()
    def live_state(self, path):
        key = self._state_key(path)
        if key not in self.live_ns_by_path:
            self.live_ns_by_path[key] = {"__name__": "__main__"}
        return self.live_ns_by_path[key]
    def executed_until(self, path):
        return self.executed_until_by_path.get(self._state_key(path), -1)
    def set_executed_until(self, path, idx):
        self.executed_until_by_path[self._state_key(path)] = idx
    def reset_live_state(self, path=None):
        "Reset the live notebook execution namespace."
        if path is None:
            self.live_ns = {"__name__": "__main__"}
            self.live_ns_by_path = {}
            self.executed_until_idx = -1
            self.executed_until_by_path = {}
            return
        self.live_ns_by_path[self._state_key(path)] = {"__name__": "__main__"}
        self.executed_until_by_path[self._state_key(path)] = -1
    def refresh_view(self):
        "Replace the notebook context message in the active Lisette history."
        if self.chat is None: return
        if self.managed_context and self.context_msg_idx is not None:
            msg = self.chat.hist[self.context_msg_idx]
            self.managed_context = managed_notebook_context(self.target_paths, self.revision, previous=self.managed_context)
            _context_msg_set(msg, "content", render_managed_context(self.managed_context))
            return
        if self.notebook_msg_idx is None: return
        msg = self.chat.hist[self.notebook_msg_idx]
        _context_msg_set(msg, "content", notebooks_view(self.target_paths, self.revision))
    def record_message(self, role, content):
        "Append one agent message to memory and the run log."
        item = {"revision": self.revision, "role": role, "content": _bounded_text(content)}
        self.messages.append(item)
        _append_agent_log(self, "message", item)
    def record(self, message):
        "Append an operation to the session log."
        self.log.append(f"r{self.revision}: {message}")
        _append_agent_log(self, "operation", {"revision": self.revision, "message": message})
    def record_tool(self, name, detail=""):
        "Append one tool use to the session history."
        detail = _bounded_text(detail, 1000) if detail else ""
        suffix = f"({detail})" if detail else "()"
        self.tool_log.append(f"r{self.revision}: {name}{suffix}")
        item = {"revision": self.revision, "tool": name}
        if detail: item["detail"] = detail
        self.history.append(item)
        _append_agent_log(self, "tool", item)
    def record_context_command(self, command, status="ok", detail=""):
        "Append one managed-context command to the session history."
        item = {"revision": self.revision, "status": status, **command}
        if detail: item["detail"] = _bounded_text(detail, 1000)
        self.context_command_log.append(item)
        _append_agent_log(self, "context_command", item)

# %% ../nbs/08_edit_interactive.ipynb #1462727f
_CTX_SIMPLE_RE = re.compile(r"\[\[ctx:(open|delete)\s+([^\]]+)\]\]")
_CTX_BLOCK_RE = re.compile(r"\[\[ctx:(fold|edit)\s+([^\]]+)\]\](.*?)\[\[/ctx:\1\]\]", re.S)


def find_context_command(text):
    "Return the first complete managed-context command in `text`."
    simple = _CTX_SIMPLE_RE.search(text)
    block = _CTX_BLOCK_RE.search(text)
    matches = [match for match in [simple, block] if match is not None]
    if not matches: return None
    match = min(matches, key=lambda item: item.start())
    if match.re is _CTX_BLOCK_RE:
        action, tag, content = match.group(1), match.group(2).strip(), match.group(3)
    else:
        action, tag, content = match.group(1), match.group(2).strip(), None
    return {
        "action": action,
        "tag": tag,
        "content": content,
        "start": match.start(),
        "end": match.end(),
        "raw": match.group(0),
    }


def _managed_message_by_tag(messages, tag):
    matches = [msg for msg in messages if msg.tag == tag]
    if len(matches) == 1: return matches[0]
    if not matches: raise ValueError(f"No managed context message has tag {tag!r}")
    raise ValueError(f"Multiple managed context messages have tag {tag!r}")


def apply_context_command(session, command):
    "Apply one managed-context command to an edit session."
    command = dict(command)
    tag, action = command.get("tag", ""), command.get("action", "")
    msg = _managed_message_by_tag(session.managed_context, tag)
    if action == "open":
        msg.visible, msg.removed = True, False
    elif action == "fold":
        summary = _bounded_text(command.get("content") or msg.summary or msg.purpose, _AGENT_MAX_MESSAGE_CHARS)
        msg.summary = summary
        msg.visible, msg.removed = False, False
    elif action == "delete":
        msg.removed, msg.visible = True, False
    elif action == "edit":
        content = _bounded_text(command.get("content") or "", _AGENT_MAX_NOTEBOOK_VIEW_CHARS)
        msg.content = content
        if not msg.purpose.startswith("edited "):
            msg.purpose = "edited " + msg.purpose
        if content.strip(): msg.summary = cap_text(" ".join(content.split()), 600)
        msg.visible, msg.removed = True, False
    else:
        raise ValueError(f"Unknown managed context action {action!r}")
    public = {key: command.get(key) for key in ("action", "tag")}
    session.record_context_command(public)
    session.refresh_view()
    return f"context {action} applied to {tag}"


def _stream_chunk_text(chunk):
    if isinstance(chunk, str): return chunk
    if isinstance(chunk, bytes): return chunk.decode("utf-8", errors="replace")
    try:
        content = chunk.choices[0].delta.content
        return "" if content is None else str(content)
    except (AttributeError, IndexError, TypeError):
        pass
    try:
        content = chunk.choices[0].message.content
        return "" if content is None else str(content)
    except (AttributeError, IndexError, TypeError):
        return ""


def _close_stream(stream):
    close = getattr(stream, "close", None)
    if callable(close): close()


def _chat_response_text(response):
    "Return assistant text from a Lisette response-like object."
    if isinstance(response, str): return response
    text = _stream_chunk_text(response)
    if text: return text
    return str(response or "")


def _chat_allows_nonstream(chat):
    "Return whether this model can recover with a non-streaming call."
    model = str(getattr(chat, "model", ""))
    return not model.startswith("chatgpt/")


def _chat_nonstream(session, prompt, max_steps):
    "Run one non-streaming continuation when provider streaming fails."
    if not _chat_allows_nonstream(session.chat):
        raise ValueError(f"{session.chat.model} requires stream=True; cannot use non-stream fallback")
    response = session.chat(prompt, max_steps=max_steps, stream=False)
    return _chat_response_text(response)


def run_chat_with_context_commands(session, prompt, max_steps=8, max_context_commands=8):
    "Run a streaming chat, intercepting managed-context text commands."
    if session.chat is None: raise ValueError("session.chat is required")
    max_steps = _bounded_int(max_steps, 8, 1, _AGENT_MAX_STEPS, "max_steps")
    max_context_commands = _bounded_int(max_context_commands, 8, 0, _AGENT_MAX_CONTEXT_COMMANDS, "max_context_commands")
    output, next_prompt = [], prompt
    for _ in range(max_context_commands + 1):
        stream = None
        try:
            stream = session.chat(next_prompt, max_steps=max_steps, stream=True)
            buffer, command = "", None
            for chunk in stream:
                piece = _stream_chunk_text(chunk)
                if not piece: continue
                buffer = cap_text(buffer + piece, _AGENT_MAX_MESSAGE_CHARS)
                command = find_context_command(buffer)
                if command:
                    _close_stream(stream)
                    break
        except BaseException as exc:
            _close_stream(stream)
            if not session.context_command_log: raise
            detail = f"{type(exc).__name__}: {exc}"
            if not _chat_allows_nonstream(session.chat): raise
            session.record_context_command(
                {"action": "fallback", "tag": "managed-context"},
                status="ok",
                detail=detail,
            )
            output.append(_chat_nonstream(session, next_prompt, max_steps=max_steps))
            return "".join(output).strip()
        if command is None:
            output.append(buffer)
            return "".join(output).strip()
        output.append(buffer[:command["start"]])
        apply_context_command(session, command)
        next_prompt = (
            f"Managed context command applied: {command['action']} {command['tag']}. "
            "Continue the same task from just before the command. Do not repeat the command."
        )
    session.record_context_command({"action": "limit", "tag": "managed-context"}, status="error", detail="max_context_commands exceeded")
    return "".join(output).strip() or "managed context command limit reached"

# %% ../nbs/08_edit_interactive.ipynb #7e5f19b2
def _none_if_blank(value):
    if value is None: return None
    value = str(value)
    return None if value.strip().lower() in {"", "none", "null"} else value

# %% ../nbs/08_edit_interactive.ipynb #ce344c69
def _edit_find_cell_by_id(cells, cell_id):
    matches = [(idx, cell) for idx, cell in enumerate(cells) if getattr(cell, "id", None) == str(cell_id)]
    if len(matches) == 1: return matches[0]
    if not matches: raise ValueError(f"No cell has id {cell_id!r}")
    raise ValueError(f"Multiple cells have id {cell_id!r}")

# %% ../nbs/08_edit_interactive.ipynb #b0789b35
def _finish_write(session, path, message, result):
    session.revision += 1
    session.reset_live_state(path)
    session.record(message)
    session.refresh_view()
    detail = str(result.get("text") or "").strip()
    chunks = [message, f"revision={session.revision}"]
    if detail: chunks.extend(["", detail])
    return "\n".join(chunks)

# %% ../nbs/08_edit_interactive.ipynb #0dbff6c2
def _agent_notebook_id(path):
    rel = Path(path).with_suffix("").as_posix()
    rel = re.sub(r"[^A-Za-z0-9_.-]+", "-", rel).strip("-.")
    return rel or "notebook"

# %% ../nbs/08_edit_interactive.ipynb #2809bf19
def _append_agent_log(session, kind, payload):
    path = Path(session.log_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "kind": kind,
        "agent_id": session.agent_id,
        "notebook": str(session.path),
        "target_notebooks": [str(path) for path in session.target_paths],
        "payload": payload,
    }
    path.open("a", encoding="utf-8").write(json.dumps(record, ensure_ascii=False) + "\n")

# %% ../nbs/08_edit_interactive.ipynb #192289a0
def _project_description(path):
    start = Path(path).resolve().parent
    for root in [start, *start.parents]:
        readme = root / "README.md"
        if readme.exists(): return cap_text(readme.read_text(encoding="utf-8"), 2400)
    return "No README.md project description was found."

# %% ../nbs/08_edit_interactive.ipynb #630fa23f
def _knowledge_context(query, top_k=3):
    try: result = reference_query(query, top_k=top_k, current_repo=".")
    except BaseException as exc: return f"Knowledge query unavailable: {type(exc).__name__}: {exc}"
    hits = []
    for hit in result.get("hits", []):
        label = ".".join(item for item in [hit.get("module"), hit.get("symbol")] if item)
        source = cap_text(hit.get("source") or hit.get("docstring") or "", 700)
        hits.append(f"- {label or hit.get('path')}: {source}")
    return "\n".join(hits) if hits else "No relevant knowledge hits."

# %% ../nbs/08_edit_interactive.ipynb #44364a03
def _symbol_impact_context(symbols):
    names = _split_notebooks(symbols)
    if not names: return "No symbols requested for caller/callee impact."
    try: return symbol_usage_summary(".", names)
    except BaseException as exc: return f"Symbol impact unavailable: {type(exc).__name__}: {exc}"

# %% ../nbs/08_edit_interactive.ipynb #7c99b181
def _subagent_context(path, plan, symbols=None):
    return "\n\n".join([
        "Project description:\n" + _project_description(path),
        "Knowledge summary:\n" + _knowledge_context(plan),
        "Caller/callee impact:\n" + _symbol_impact_context(symbols),
    ])

# %% ../nbs/08_edit_interactive.ipynb #8ef57685
def _inserted_cell_ids(result):
    inserted = []
    for diff in result.get("diffs", []):
        inserted.extend(diff.get("inserted_cell_ids", []))
    return inserted


def make_edit_tools(session):
    "Create notebook-scoped editing tools for one edit-interactive session."

    def str_replace(old_str: str, new_str: str, notebook: str | None = None) -> str:
        "Replace one exact string occurrence anywhere in a target notebook."
        path = session.target_path(notebook)
        with notebook_locks(path):
            nb = read_nb(path)
            matches = []
            for idx, cell in enumerate(nb.cells):
                source = cell_source(cell)
                if old_str in source:
                    matches.append((idx, cell, source))
        session.record_tool("str_replace", f"notebook={path}, matches={len(matches)}")
        if len(matches) != 1:
            raise ValueError(
                f"old_str matched {len(matches)} cells in {path}; expected exactly 1"
            )
        idx, cell, before = matches[0]
        after = before.replace(old_str, new_str, 1)
        result = NotebookEditor(path, auto_feedback=False).replace_cell(
            cell.id, after, cell_type=cell.cell_type
        )
        msg = f"Replaced text in {path} id={cell.id}"
        return _finish_write(session, path, msg, result)

    def edit_cell(
        id: str, old_str: str, new_str: str, notebook: str | None = None
    ) -> str:
        "Replace one exact string occurrence inside one cell."
        path = session.target_path(notebook)
        with notebook_locks(path):
            nb = read_nb(path)
            idx, cell = _edit_find_cell_by_id(nb.cells, id)
            before = cell_source(cell)
            count = before.count(old_str)
        session.record_tool("edit_cell", f"notebook={path}, id={id!r}, matches={count}")
        if count != 1:
            raise ValueError(
                f"old_str matched {count} times in {path} id={id}; expected exactly 1"
            )
        after = before.replace(old_str, new_str, 1)
        result = NotebookEditor(path, auto_feedback=False).replace_cell(
            id, after, cell_type=cell.cell_type
        )
        msg = f"Edited text in {path} id={id}"
        return _finish_write(session, path, msg, result)

    def add_cell(
        after_id: str | None = None,
        content: str = "",
        notebook: str | None = None,
    ) -> str:
        "Add one cell to a target notebook."
        path = session.target_path(notebook)
        anchor = _none_if_blank(after_id)
        new_cell = parse_one_cell(content, "code")
        if anchor is not None:
            with notebook_locks(path):
                _edit_find_cell_by_id(read_nb(path).cells, anchor)
        session.record_tool("add_cell", f"notebook={path}, after_id={anchor!r}")
        result = NotebookEditor(path, auto_feedback=False).insert(
            anchor, cell_source(new_cell), cell_type=new_cell.cell_type
        )
        inserted = _inserted_cell_ids(result)
        new_id = inserted[0] if inserted else ""
        where = f"after id={anchor}" if anchor is not None else "at end"
        msg = f"Added cell id={new_id} to {path} {where}"
        return _finish_write(session, path, msg, result)

    def delete_cell(id: str, notebook: str | None = None) -> str:
        "Delete one cell from a target notebook."
        path = session.target_path(notebook)
        with notebook_locks(path):
            _edit_find_cell_by_id(read_nb(path).cells, id)
        session.record_tool("delete_cell", f"notebook={path}, id={id!r}")
        result = NotebookEditor(path, auto_feedback=False).delete(id)
        msg = f"Deleted cell id={id} from {path}"
        return _finish_write(session, path, msg, result)

    def _exec_python(source, filename, ns):
        tree = ast.parse(source, filename=filename, mode="exec")
        if not tree.body:
            return None
        if not isinstance(tree.body[-1], ast.Expr):
            exec(compile(tree, filename, "exec"), ns)
            return None
        prefix = ast.Module(body=tree.body[:-1], type_ignores=[])
        expr = ast.Expression(tree.body[-1].value)
        ast.fix_missing_locations(prefix)
        ast.fix_missing_locations(expr)
        if prefix.body:
            exec(compile(prefix, filename, "exec"), ns)
        return eval(compile(expr, filename, "eval"), ns)

    def _eval_false(source):
        return any(
            re.match(r"#\|\s*eval:\s*false\b", line.strip(), re.I)
            for line in source.splitlines()[:5]
        )

    def _time_limit_supported():
        return (
            hasattr(signal, "setitimer")
            and hasattr(signal, "SIGALRM")
            and current_thread() is main_thread()
        )

    @contextmanager
    def _time_limit(seconds):
        def _raise_timeout(signum, frame):
            raise TimeoutError(f"execution exceeded budget_secs={seconds}")

        old_handler = signal.signal(signal.SIGALRM, _raise_timeout)
        old_timer = signal.setitimer(signal.ITIMER_REAL, float(seconds))
        try:
            yield
        finally:
            signal.setitimer(signal.ITIMER_REAL, 0)
            signal.signal(signal.SIGALRM, old_handler)
            if old_timer[0] > 0:
                signal.setitimer(signal.ITIMER_REAL, old_timer[0], old_timer[1])

    @contextmanager
    def _execution_budget(seconds, explicit):
        if not _time_limit_supported():
            if explicit:
                raise RuntimeError(
                    "execution timeout unsupported: signal timers require the main thread"
                )
            yield
            return
        with _time_limit(seconds):
            yield

    def _execute_source(source, header, filename, ns, budget_secs=None):
        budget = _bounded_int(
            budget_secs,
            session.timeout,
            1,
            _AGENT_MAX_TIMEOUT_SECONDS,
            "budget_secs",
        )
        out, err = StringIO(), StringIO()
        status, display, tb = "ok", None, ""
        try:
            with (
                _execution_budget(budget, budget_secs is not None),
                _CAPTURE_LOCK,
                redirect_stdout(out),
                redirect_stderr(err),
            ):
                display = _exec_python(source, filename, ns)
        except BaseException:
            status = "error"
            tb = traceback.format_exc()
        chunks = [f"{header} status={status} budget_secs={budget}"]
        if out.getvalue():
            chunks.append("stdout:\n" + out.getvalue().rstrip())
        if err.getvalue():
            chunks.append("stderr:\n" + err.getvalue().rstrip())
        if display is not None:
            chunks.append("display:\n" + repr(display))
        if tb:
            chunks.append("traceback:\n" + tb.rstrip())
        return "\n".join(chunks)

    def run_code(
        source: str, notebook: str | None = None, budget_secs: int | None = None
    ) -> str:
        "Run scratch Python in the live notebook scope without editing the notebook."
        path = session.target_path(notebook)
        budget = _bounded_int(
            budget_secs,
            session.timeout,
            1,
            _AGENT_MAX_TIMEOUT_SECONDS,
            "budget_secs",
        )
        source = str(source or "")
        session.record_tool(
            "run_code", f"notebook={path}, chars={len(source)}, budget_secs={budget}"
        )
        report = _execute_source(
            source,
            f"SCRATCH notebook={path}",
            f"{path}::<scratch>",
            session.live_state(path),
            budget_secs,
        )
        status = "error" if " status=error" in report else "ok"
        session.record(f"Ran scratch code in {path} ({status})")
        return report

    def inspect_state(name: str | None = None, notebook: str | None = None) -> str:
        "Inspect variables and functions in the live notebook scope."
        path = session.target_path(notebook)
        ns = session.live_state(path)
        target = _none_if_blank(name)
        session.record_tool("inspect_state", f"notebook={path}, name={target!r}")
        if target is None:
            names = sorted(key for key in ns if not key.startswith("__"))
            lines = [f"state notebook={path} names={len(names)}"]
            lines.extend(f"- {key}: {type(ns[key]).__name__}" for key in names)
            return "\n".join(lines)
        if target not in ns:
            return f"state notebook={path} name={target} status=missing"
        value = ns[target]
        value_type = type(value)
        lines = [
            f"state notebook={path} name={target} status=ok",
            f"type={value_type.__module__}.{value_type.__qualname__}",
            "repr=" + cap_text(repr(value), 2000),
        ]
        if callable(value):
            try:
                lines.append(f"signature={target}{inspect.signature(value)}")
            except (TypeError, ValueError):
                pass
        try:
            source = inspect.getsource(value)
        except (OSError, TypeError):
            source = ""
        if source:
            lines.append("source:\n" + cap_text(source, 4000))
        return "\n".join(lines)

    def _execute_one(path, idx, cell, budget_secs=None):
        source = cell_source(cell)
        header = f"CELL {idx} id={cell.id} notebook={path}"
        if cell.cell_type != "code":
            return f"{header} status=skipped reason=non-code"
        if _eval_false(source):
            return f"{header} status=skipped reason=eval-false"
        return _execute_source(
            source,
            header,
            f"{path}::{cell.id}",
            session.live_state(path),
            budget_secs,
        )

    def execute_cell(
        id: str,
        rerun_all: bool = False,
        notebook: str | None = None,
        budget_secs: int | None = None,
    ) -> str:
        "Execute through one cell in the live notebook state."
        path = session.target_path(notebook)
        with notebook_locks(path):
            nb = read_nb(path)
            target_idx, _ = _edit_find_cell_by_id(nb.cells, id)
            cells = list(nb.cells)
        if rerun_all:
            session.reset_live_state(path)
        start = session.executed_until(path) + 1
        if target_idx < start:
            start = target_idx
        budget = _bounded_int(
            budget_secs,
            session.timeout,
            1,
            _AGENT_MAX_TIMEOUT_SECONDS,
            "budget_secs",
        )
        session.record_tool(
            "execute_cell",
            (
                f"notebook={path}, id={id!r}, rerun_all={rerun_all}, "
                f"budget_secs={budget}, start={start}, target={target_idx}"
            ),
        )
        reports, status = [], "ok"
        for idx in range(start, target_idx + 1):
            report = _execute_one(path, idx, cells[idx], budget_secs=budget_secs)
            reports.append(report)
            session.set_executed_until(path, idx)
            if " status=error" in report:
                status = "error"
                break
        if not reports:
            reports.append(
                f"CELL {target_idx} id={id} notebook={path} "
                "status=skipped reason=already-executed"
            )
        session.record(f"Executed {path} cells {start}:{target_idx} ({status})")
        return "\n\n".join([f"status={status}", *reports])

    def query_knowledge(query: str, top_k: int = 3) -> str:
        "Search the reference knowledge base."
        session.record_tool("query_knowledge", f"top_k={top_k}")
        return _knowledge_context(query, top_k=top_k)

    return [
        str_replace,
        edit_cell,
        add_cell,
        delete_cell,
        run_code,
        inspect_state,
        execute_cell,
        query_knowledge,
    ]

# %% ../nbs/08_edit_interactive.ipynb #3540e8d9
def make_context_tools(session):
    "Create managed-context tools for a separate context session."

    def open_context(tag: str) -> str:
        "Open a folded managed-context message."
        return apply_context_command(session, {"action": "open", "tag": tag})

    def fold_context(tag: str, summary: str) -> str:
        "Fold a managed-context message to a concise summary."
        return apply_context_command(
            session, {"action": "fold", "tag": tag, "content": summary}
        )

    def delete_context(tag: str) -> str:
        "Delete a managed-context message from active renders."
        return apply_context_command(session, {"action": "delete", "tag": tag})

    def edit_context(tag: str, content: str) -> str:
        "Replace one managed-context message with custom content."
        return apply_context_command(
            session, {"action": "edit", "tag": tag, "content": content}
        )

    def context_view() -> str:
        "Return the currently active managed context."
        session.record_context_command({"action": "view", "tag": "managed-context"})
        return render_managed_context(session.managed_context)

    return [open_context, fold_context, delete_context, edit_context, context_view]


def make_chat(model, tools, hist, system_prompt=EDIT_INTERACTIVE_SYSTEM):
    "Create the Lisette chat object for edit-interactive."
    from lisette import Chat

    return Chat(
        model, sp=system_prompt, tools=tools, hist=hist, stream=str(model).startswith("chatgpt/")
    )


def run_context_session(session, model, prompt, max_steps=4, max_context_commands=8):
    "Run one separate context-management step and restore the active edit chat."
    if not session.managed_context:
        return ""
    max_steps = _bounded_int(max_steps, 4, 0, _AGENT_MAX_CONTEXT_STEPS, "max_steps")
    max_context_commands = _bounded_int(
        max_context_commands,
        8,
        0,
        _AGENT_MAX_CONTEXT_COMMANDS,
        "max_context_commands",
    )
    if max_steps == 0:
        return ""
    prior_chat, prior_context_idx = session.chat, session.context_msg_idx
    hist = [{"role": "user", "content": render_managed_context(session.managed_context)}]
    chat = make_chat(
        model,
        tools=make_context_tools(session),
        hist=hist,
        system_prompt=CONTEXT_SESSION_SYSTEM,
    )
    session.chat = chat
    session.context_msg_idx = len(chat.hist) - 1
    try:
        if max_context_commands:
            result = run_chat_with_context_commands(
                session,
                prompt,
                max_steps=max_steps,
                max_context_commands=max_context_commands,
            )
        else:
            result = chat(prompt, max_steps=max_steps, return_all=True)
    except BaseException as exc:
        summary = f"context session failed: {type(exc).__name__}: {exc}"
    else:
        summary = _bounded_text(response_text(result).strip() or "(no context response)")
    finally:
        session.chat, session.context_msg_idx = prior_chat, prior_context_idx
    session.record_message("context", summary)
    return summary

# %% ../nbs/08_edit_interactive.ipynb #7b3292af
def response_text(response):
    "Extract readable text from a Lisette response or response list."
    if isinstance(response, list) and response: response = response[-1]
    try:
        message = response.choices[0].message
        content = message.content
    except (AttributeError, IndexError, TypeError):
        return "" if response is None else str(response)
    if isinstance(content, list):
        return "".join(str(item.get("text", item)) if isinstance(item, dict) else str(item) for item in content)
    return "" if content is None else str(content)


def plan_result_text(result):
    "Return the human-readable text for an execute_plan result."
    if not isinstance(result, dict): return "" if result is None else str(result)
    if result.get("text"): return str(result["text"])
    sections = [
        "edit-interactive complete",
        "",
        "Final response:",
        str(result.get("summary") or "(no final response)"),
        "",
        "Tools used:",
        "\n".join(item.get("detail", item.get("tool", "")) for item in result.get("history", [])) or "(no tool calls)",
    ]
    return "\n".join(sections).rstrip()

# %% ../nbs/08_edit_interactive.ipynb #5b4daf87
def final_diff(path):
    "Return a nbdev code-cell diff, or a clear unavailable message."
    try:
        with notebook_locks(path):
            return cap_text(capture_call_text(diff_nb, path=str(path)), _AGENT_MAX_DIFF_CHARS)
    except BaseException as exc:
        detail = str(exc)
        if "Could not find notebook" in detail or "No git repository found" in detail:
            return (
                "Code-cell diff against HEAD is unavailable because this notebook has no git baseline. "
                "This is expected for new or untracked notebooks."
            )
        return f"Code-cell diff unavailable: {type(exc).__name__}: {exc}"


def final_diffs(paths):
    "Return code-cell diffs for one or more notebooks."
    chunks = []
    for path in _target_paths(paths):
        chunks.extend([f"## {path}", final_diff(path).strip()])
    return cap_text("\n\n".join(chunks).rstrip(), _AGENT_MAX_DIFF_CHARS)

# %% ../nbs/08_edit_interactive.ipynb #c1425865
def execute_plan(
    notebook: str | list,
    plan: str,
    model: str | None = None,
    max_steps: int = 8,
    timeout: int = 30,
    dry_run: bool = False,
    symbols: str | None = None,
    injected_context: str | None = None,
    max_context_commands: int = 8,
    context_steps: int = 2,
) -> dict:
    "Execute `plan` against one or more notebooks using bounded subagent steps."
    paths = _target_paths(notebook)
    missing = [str(path) for path in paths if not path.exists()]
    if missing:
        raise ValueError(f"Notebook does not exist: {', '.join(missing)}")
    max_steps = _bounded_int(max_steps, 8, 1, _AGENT_MAX_STEPS, "max_steps")
    timeout = _bounded_int(timeout, 30, 1, _AGENT_MAX_TIMEOUT_SECONDS, "timeout")
    max_context_commands = _bounded_int(
        max_context_commands,
        8,
        0,
        _AGENT_MAX_CONTEXT_COMMANDS,
        "max_context_commands",
    )
    context_steps = _bounded_int(
        context_steps, 2, 0, _AGENT_MAX_CONTEXT_STEPS, "context_steps"
    )
    model = model or os.environ.get("NBSKILL_AGENT") or "chatgpt/gpt-5.4-mini"
    project_context = _bounded_text(
        injected_context or _subagent_context(paths[0], plan, symbols=symbols)
    )
    initial_messages = managed_notebook_context(paths, revision=0)
    initial_view = cap_text(
        render_managed_context(initial_messages), _AGENT_MAX_NOTEBOOK_VIEW_CHARS
    )
    if dry_run:
        text = "\n".join(
            [
                "notebook subagent dry run",
                "",
                f"Notebooks: {_target_label(paths)}",
                f"Model: {model}",
                f"Max steps: {max_steps}",
                "Plan:",
                plan,
                "",
                "Injected project context:",
                project_context,
                "",
                "Initial managed notebook context:",
                initial_view,
            ]
        ).rstrip()
        return {
            "summary": "Dry run only; no subagent was invoked and no notebook edits were made.",
            "history": [],
            "context_commands": [],
            "text": cap_text(text, _AGENT_MAX_NOTEBOOK_VIEW_CHARS),
        }
    session = EditSession(
        path=paths, target_paths=paths, timeout=timeout, managed_context=initial_messages
    )
    prep = (
        "Prepare context for the edit step. Open only chapters likely needed for this plan.\n"
        "Plan:\n" + plan
    )
    run_context_session(
        session,
        model,
        prep,
        max_steps=context_steps,
        max_context_commands=max_context_commands,
    )
    initial_view = cap_text(
        render_managed_context(session.managed_context), _AGENT_MAX_NOTEBOOK_VIEW_CHARS
    )
    hist = [
        {"role": "user", "content": "Injected project context:\n" + project_context},
        {"role": "user", "content": f"Plan:\n{plan}"},
        {"role": "user", "content": initial_view},
    ]
    for item in hist:
        session.record_message(item["role"], item["content"])
    chat = make_chat(model, tools=make_edit_tools(session), hist=hist)
    session.chat = chat
    session.context_msg_idx = len(chat.hist) - 1
    session.refresh_view()
    prompt = (
        "Execute the plan with the scratch, inspect, function, example, and test "
        "loop from the system prompt. Use run_code for experiments, inspect_state "
        "for live state checks, and execute_cell to validate the final example or "
        "test when practical. Context-management tools are not available in this edit "
        "step; use the active context you were given. Stop when the notebook change "
        "is complete."
    )
    session.record_message("user", prompt)
    try:
        result = chat(prompt, max_steps=max_steps, return_all=True)
    except BaseException as exc:
        result = f"notebook subagent failed: {type(exc).__name__}: {exc}"
    if not isinstance(result, (list, str, bytes, dict)) and hasattr(result, "__next__"):
        result = list(result)
    summary = _bounded_text(response_text(result).strip() or "(no final response)")
    session.record_message("assistant", summary)
    cleanup = (
        "Clean up context after the edit step. Fold useful full chapters to summaries, "
        "delete irrelevant scratch context from active renders, and leave the index visible."
    )
    run_context_session(
        session,
        model,
        cleanup,
        max_steps=context_steps,
        max_context_commands=max_context_commands,
    )
    for path in paths:
        _save_notebook(read_nb(path), path)
    session.record("Exported notebook(s) after subagent run")
    diff = final_diffs(paths).strip()
    text = "\n".join(
        [
            "notebook subagent complete",
            "",
            "Final response:",
            summary,
            "",
            "Tools used:",
            "\n".join(_bounded_items(session.tool_log))
            if session.tool_log
            else "(no tool calls)",
            "",
            "Context commands:",
            "\n".join(
                f"r{item['revision']}: {item['action']} {item['tag']} ({item['status']})"
                for item in _bounded_items(session.context_command_log)
            )
            if session.context_command_log
            else "(no context commands)",
            "",
            "Operation log:",
            "\n".join(_bounded_items(session.log))
            if session.log
            else "(no notebook operations)",
            "",
            f"Final revision: {session.revision}",
            f"Agent log: {session.log_path}",
            "",
            "Notebook diff:",
            diff,
        ]
    ).rstrip()
    return {
        "summary": summary,
        "history": _bounded_items(session.history),
        "context_commands": _bounded_items(session.context_command_log),
        "messages": _bounded_items(session.messages),
        "text": cap_text(text, _AGENT_MAX_NOTEBOOK_VIEW_CHARS),
        "model": model,
        "notebook": str(paths[0]),
        "notebooks": [str(path) for path in paths],
        "revision": session.revision,
        "operations": _bounded_items(session.log),
        "log_path": str(session.log_path),
        "diff": diff,
    }

# %% ../nbs/08_edit_interactive.ipynb #256a672a
# `_split_notebooks` is defined near the notebook rendering helpers because both context and execution use it.

# %% ../nbs/08_edit_interactive.ipynb #43a4eae6
def execute_project_plan(
    plan: str,
    notebooks: str | None = None,
    model: str | None = None,
    max_steps: int = 8,
    timeout: int = 30,
    dry_run: bool = True,
    symbols: str | None = None,
) -> str:
    "Launch one edit-interactive session that can touch multiple notebooks."
    targets = _split_notebooks(notebooks)
    if not targets: raise ValueError("Pass one or more notebooks to execute_project_plan.")
    result = execute_plan(
        notebook=targets, plan=plan, model=model, max_steps=max_steps,
        timeout=timeout, dry_run=dry_run, symbols=symbols,
    )
    return "\n".join([
        "project subagent coordinator", "", f"Dry run: {dry_run}", f"Targets: {len(targets)}", "", plan_result_text(result),
    ]).rstrip()
