# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_execute.ipynb.

# %% auto #0
__all__ = ['exec_nb']

# %% ../nbs/03_execute.ipynb #2a4844d2
import sys
from pathlib import Path

from execnb.shell import CaptureShell
from fastcore.nbio import read_nb as _read_nb
from fastcore.script import call_parse

from .foundation import _cli_error, _cli_return, _one_chapter, _parse_literal, _tracked_call

# %% ../nbs/03_execute.ipynb #d43ace86
def _exec_limiters(up2id):
    up2id = _parse_literal(up2id)
    noop = lambda cell: None
    if up2id is None: return (lambda cell: False), noop
    if isinstance(up2id, int):
        if up2id < 0: raise ValueError("up2id must be >= 0")
        return (lambda cell: cell.idx_ >= up2id), noop

    done = False
    def preproc(cell): return done
    def postproc(cell):
        nonlocal done
        if cell.id == str(up2id): done = True
    return preproc, postproc

# %% ../nbs/03_execute.ipynb #1280fb89
def _project_root_for_notebook(path):
    path = Path(path).resolve()
    start = path.parent if path.suffix else path
    markers = ("pyproject.toml", "settings.ini", "nbdev.yml", ".git")
    for folder in (start, *start.parents):
        if any((folder / marker).exists() for marker in markers): return folder
    if start.name in {"nbs", "notebooks"} and start.parent != start.parent.parent: return start.parent
    return start

# %% ../nbs/03_execute.ipynb #ff02175a
def _local_import_paths(path):
    nb_dir = Path(path).resolve().parent
    root = _project_root_for_notebook(path)
    paths = [nb_dir, root]
    src = root / "src"
    if src.exists(): paths.append(src)
    return [p for i, p in enumerate(paths) if p.exists() and p not in paths[:i]]

# %% ../nbs/03_execute.ipynb #8fde5f5d
def _exec_shell(path, extra_paths=None):
    shell = CaptureShell()
    for pth in reversed([*(_local_import_paths(path)), *(extra_paths or [])]):
        shell.set_path(pth)
    return shell

# %% ../nbs/03_execute.ipynb #1e0af2c5
def _text_output(value):
    if value is None: return ""
    if isinstance(value, list): return "".join(map(str, value))
    return str(value)


def _output_text(output):
    otype = output.get("output_type")
    if otype == "stream": return _text_output(output.get("text"))
    if otype == "error":
        tb = output.get("traceback")
        if tb: return _text_output(tb)
        return f"{output.get('ename', 'Error')}: {output.get('evalue', '')}"
    if otype in {"execute_result", "display_data"}:
        data = output.get("data", {})
        for mime in ("text/plain", "text/markdown", "text/html"):
            if mime in data: return _text_output(data[mime])
    return ""


def _is_rich_traceback_stream(output):
    if output.get("output_type") != "stream": return False
    text = _text_output(output.get("text"))
    return "Traceback" in text and "\x1b[" in text


def _executed_cells(nb, up2id=None):
    up2id = _parse_literal(up2id)
    if up2id is None: return list(enumerate(nb.cells))
    if isinstance(up2id, int): return list(enumerate(nb.cells[:up2id]))
    items = []
    for idx, cell in enumerate(nb.cells):
        items.append((idx, cell))
        if cell.id == str(up2id): break
    return items


def _print_nb_outputs(path, up2id=None):
    nb = _read_nb(path)
    for idx, cell in _executed_cells(nb, up2id):
        outputs = getattr(cell, "outputs", None) or []
        has_error = any(output.get("output_type") == "error" for output in outputs)
        for output in outputs:
            if has_error and _is_rich_traceback_stream(output): continue
            text = _output_text(output)
            if not text: continue
            print(f"--- output id={cell.id} ---")
            print(text, end="" if text.endswith("\n") else "\n")

# %% ../nbs/03_execute.ipynb #434c13b3
@call_parse
@_tracked_call
def exec_nb(
    path: str,  # Notebook path
    dest: str | None = None,  # Destination path; defaults to overwriting path
    exc_stop: bool = False,  # Stop on exceptions
    up2id: int | str | None = None,  # Execute first N cells, or through this cell id
    chapter: str | None = None,  # Execute through this chapter, inclusive
    show_output: bool = True,  # Print saved cell outputs and errors after execution
    verbose: bool = False,  # Show stdout/stderr live while executing
):
    "Execute a notebook with execnb and local project imports available."
    dest = dest or path
    chapter_title = None
    if chapter is not None:
        if up2id is not None: raise ValueError("Use either chapter or up2id, not both")
        nb = _read_nb(path)
        span = _one_chapter(nb.cells, chapter)
        up2id, chapter_title = span["end"], span["title"]
    preproc, postproc = _exec_limiters(up2id)
    shell = _exec_shell(path)
    shell.execute(path, dest=dest, exc_stop=exc_stop, preproc=preproc, postproc=postproc, verbose=verbose)
    msg = f"Executed {path} -> {dest}"
    if chapter_title is not None: msg += f" (chapter={chapter_title!r}, up2id={up2id})"
    elif up2id is not None: msg += f" (up2id={up2id})"
    print(msg)
    if show_output: _print_nb_outputs(dest, up2id=up2id)
    return _cli_return(Path(dest))

# %% ../nbs/03_execute.ipynb #e9c50752
def _notebook_error_summaries(path, up2id=None):
    nb = _read_nb(path)
    errors = []
    for idx, cell in _executed_cells(nb, up2id=up2id):
        for output in cell.get("outputs", []):
            if output.get("output_type") == "error":
                ename = output.get("ename", "Error")
                evalue = output.get("evalue", "")
                errors.append(f"id={cell.id} {ename}: {evalue}".strip())
    return errors

# %% ../nbs/03_execute.ipynb #891fb269
def _run_notebook_test(path):
    print(f"Running notebook test with execnb on {path}")
    _exec_shell(path).execute(path, dest=path, exc_stop=False, verbose=False)
    _print_nb_outputs(path)
    errors = _notebook_error_summaries(path)
    if errors:
        sys.stdout.flush()
        _cli_error("Notebook test failed after writing/execution: " + "; ".join(errors))
