# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_knowledge.ipynb.

# %% auto #0
__all__ = ['default_knowledge', 'knowledge_path', 'load_knowledge', 'store_knowledge', 'add_behaviour_steering', 'get_knowledge',
           'knowledge_style_problems']

# %% ../nbs/12_knowledge.ipynb #911ef06b
import glob,json,os,re,time
from pathlib import Path

from fastcore.nbio import read_nb
from fastcore.script import call_parse

from .foundation import cell_source, cli_return, tracked_call

# %% ../nbs/12_knowledge.ipynb #knowdefaults1
_DEFAULT_BEHAVIOURS = [
    {
        "id": "avoid-aliased-function-imports",
        "regex": r"from\s+\S+\s+import\s+\w+\s+as\s+\w+",
        "note": "Do not import functions by alias unless it is needed to avoid a real conflict.",
        "source": "default",
    },
    {
        "id": "avoid-wildcard-imports",
        "regex": r"from\s+\S+\s+import\s+\*",
        "note": "Avoid wildcard imports; import the names used by the cell.",
        "source": "default",
    },
    {
        "id": "avoid-shell-true",
        "regex": r"subprocess\.(run|Popen|call|check_call|check_output)\([^)]*shell\s*=\s*True",
        "note": "Avoid shell=True unless shell behavior is explicitly required.",
        "source": "default",
    },
]


# %% ../nbs/12_knowledge.ipynb #knowdefaults2
_DEFAULT_BEHAVIOURS += [
    {
        "id": "avoid-eval-exec",
        "regex": r"\b(eval|exec)\s*\(",
        "note": "Avoid eval/exec unless dynamic execution is the actual goal.",
        "source": "default",
    },
    {
        "id": "avoid-destructive-git",
        "regex": r"git\s+(reset\s+--hard|clean\s+-fd|checkout\s+--)",
        "note": "Do not run destructive git cleanup commands unless the user explicitly asked for them.",
        "source": "default",
    },
]


# %% ../nbs/12_knowledge.ipynb #0e70336e
def default_knowledge():
    "Return built-in behaviour steering examples."
    return {"version": 1, "behaviours": [dict(item) for item in _DEFAULT_BEHAVIOURS]}


# %% ../nbs/12_knowledge.ipynb #eec52384
def knowledge_path(path=None):
    "Return the JSON file used for behaviour steering memory."
    default = Path.home() / ".nbskill-knowledge.json"
    return Path(path or os.environ.get("NBSKILL_KNOWLEDGE_PATH", default)).expanduser()

# %% ../nbs/12_knowledge.ipynb #24eb4a7a
def _empty_knowledge():
    return {"version": 1, "behaviours": []}

# %% ../nbs/12_knowledge.ipynb #c48198fc
def _defaults_enabled():
    return os.environ.get("NBSKILL_KNOWLEDGE_DEFAULTS", "1").lower() not in {"0", "false", "no"}

# %% ../nbs/12_knowledge.ipynb #9845842a
def _merge_behaviours(*groups):
    seen, behaviours = set(), []
    for group in groups:
        for item in group:
            key = item.get("id") or item.get("regex")
            if key in seen: continue
            seen.add(key)
            behaviours.append(dict(item))
    return behaviours

# %% ../nbs/12_knowledge.ipynb #f5a32a61
def _load_user_knowledge(path=None):
    pth = knowledge_path(path)
    try: data = json.loads(pth.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError): data = _empty_knowledge()
    data.setdefault("version", 1)
    data.setdefault("behaviours", [])
    return data

# %% ../nbs/12_knowledge.ipynb #cdcdcdc8
def load_knowledge(path=None, include_defaults=True):
    "Load behaviour steering rules from defaults and the JSON memory file."
    data = _load_user_knowledge(path)
    if include_defaults and _defaults_enabled():
        data["behaviours"] = _merge_behaviours(default_knowledge()["behaviours"], data.get("behaviours", []))
    return data

# %% ../nbs/12_knowledge.ipynb #e42b722d
def _write_knowledge(data, path=None):
    pth = knowledge_path(path)
    pth.parent.mkdir(parents=True, exist_ok=True)
    pth.write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")
    return pth

# %% ../nbs/12_knowledge.ipynb #7b7d051d
def _check_regex(pattern):
    re.compile(pattern)
    return pattern

# %% ../nbs/12_knowledge.ipynb #32f017c7
def _print_json(value):
    print(json.dumps(value, indent=2, sort_keys=True))

# %% ../nbs/12_knowledge.ipynb #2852fabc
@call_parse
@tracked_call
def store_knowledge(
    apply_regex: str,  # Regex to apply to notebook code cells
    note: str,  # Behaviour note shown when the regex matches
    path: str | None = None,  # Override JSON memory path
):
    "Store or update one behaviour steering regex and note."
    _check_regex(apply_regex)
    data = _load_user_knowledge(path)
    now = time.time()
    item = {"regex": apply_regex, "note": note, "updated_ts": now}
    for idx, existing in enumerate(data["behaviours"]):
        if existing.get("regex") == apply_regex:
            item["created_ts"] = existing.get("created_ts", now)
            data["behaviours"][idx] = {**existing, **item}
            break
    else:
        item["created_ts"] = now
        data["behaviours"].append(item)
    pth = _write_knowledge(data, path)
    result = {"path": str(pth), "stored": item, "count": len(data["behaviours"])}
    _print_json(result)
    return cli_return(result)

# %% ../nbs/12_knowledge.ipynb #4a4befe6
@call_parse
@tracked_call
def add_behaviour_steering(
    regex: str,  # Regex the agent created from a behaviour note
    path: str | None = None,  # Override JSON memory path
):
    "Add a behaviour steering regex with a generic note."
    return store_knowledge(regex, f"Behaviour steering matched: {regex}", path=path)

# %% ../nbs/12_knowledge.ipynb #3ae65303
@call_parse
@tracked_call
def get_knowledge(
    regex: str | None = None,  # Optional regex for filtering stored regexes and notes
    path: str | None = None,  # Override JSON memory path
    include_defaults: bool = True,  # Include built-in example behaviours
):
    "Return stored behaviour steering rules, optionally filtered by regex."
    data = load_knowledge(path, include_defaults=include_defaults)
    items = data.get("behaviours", [])
    if regex:
        query_re = re.compile(_check_regex(regex))
        items = [item for item in items if query_re.search(item.get("regex", "")) or query_re.search(item.get("note", ""))]
    result = {"path": str(knowledge_path(path)), "count": len(items), "behaviours": items}
    _print_json(result)
    return cli_return(result)

# %% ../nbs/12_knowledge.ipynb #bccae447
def _is_notebook_path(path):
    path = Path(path)
    return path.suffix == ".ipynb" and ".ipynb_checkpoints" not in path.parts

# %% ../nbs/12_knowledge.ipynb #3691696d
def _notebook_paths(path="."):
    raw = str(path)
    pth = Path(raw).expanduser()
    if any(char in raw for char in "*?[]"): candidates = [Path(item) for item in glob.glob(raw, recursive=True)]
    elif pth.is_dir(): candidates = list(pth.rglob("*.ipynb"))
    elif pth.is_file() and pth.suffix == ".ipynb": candidates = [pth]
    else: candidates = []
    return sorted({candidate for candidate in candidates if _is_notebook_path(candidate)})

# %% ../nbs/12_knowledge.ipynb #f75beda0
def _line_for_match(source, match):
    return source.count("\n", 0, match.start()) + 1

# %% ../nbs/12_knowledge.ipynb #60b84ac7
def _knowledge_problem(nb_path, cell, line, item, match):
    note = item.get("note", "")
    return {
        "code": "knowledge-warning",
        "path": str(nb_path),
        "severity": "warning",
        "source": "nbskill-knowledge",
        "detail": "stored behaviour steering rule matched",
        "cell_id": getattr(cell, "id", ""),
        "line": line,
        "regex": item.get("regex", ""),
        "note": note,
        "match": match.group(0).splitlines()[0][:160],
    }

# %% ../nbs/12_knowledge.ipynb #91ec740f
def knowledge_style_problems(path=".", knowledge_path_override=None):
    "Return style diagnostics for stored behaviour steering regex matches."
    rules = load_knowledge(knowledge_path_override).get("behaviours", [])
    compiled = [(item, re.compile(item["regex"], re.MULTILINE)) for item in rules if item.get("regex")]
    if not compiled: return []
    problems = []
    for nb_path in _notebook_paths(path):
        try: nb = read_nb(nb_path)
        except FileNotFoundError: continue
        for cell in nb.cells:
            if getattr(cell, "cell_type", None) != "code": continue
            source = cell_source(cell)
            for item, pattern in compiled:
                for match in pattern.finditer(source):
                    problems.append(_knowledge_problem(nb_path, cell, _line_for_match(source, match), item, match))
    return problems
