# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_mcp.ipynb.

# %% auto #0
__all__ = ['mcp', 'as_text', 'capture_call', 'capture_notebook_call', 'mcp_tool_result', 'nbskill_status', 'doctor_tool',
           'edit_cell_tool', 'edit_cell_range_tool', 'insert_cells_tool', 'apply_notebook_edits_tool', 'exec_nb_tool',
           'execute_plan_tool', 'agent_workbench_tool', 'style_check_tool', 'py2nb_tool', 'new_nbdev_notebook_tool',
           'create_mcp', 'main']

# %% ../nbs/07_mcp.ipynb #mcpimports1
import hashlib,json,os
import re
import shutil
import subprocess
import sys
import threading
import time
from contextlib import redirect_stdout, redirect_stderr
from importlib.metadata import PackageNotFoundError, version
from io import StringIO
from pathlib import Path

# %% ../nbs/07_mcp.ipynb #mcpimports2
from fastcore.nbio import read_nb as _read_raw_nb
from fastcore.script import _in_call_parse
from fastmcp import FastMCP
from fastmcp.tools import ToolResult
from mcp.types import TextContent

# %% ../nbs/07_mcp.ipynb #mcpimports3
from .convert import new_nbdev_notebook
from .convert import py2nb
from .convert import py2nbdev
from .edit_interactive import execute_plan
from .edit_interactive import execute_project_plan
from .edit_interactive import plan_result_text
from .execute import exec_nb
from .workbench import agent_workbench_result
from .foundation import empty_failure_map, failure_map_path, load_failure_map
from .foundation import cell_source, exported_py_path, generated_owner, git_root, git_status_paths, notebook_paths, path_candidates

# %% ../nbs/07_mcp.ipynb #mcpimports4
from .graph import notebook_order_problems
from .graph import private_symbol_report
from .graph import symbol_graph_data, symbol_graph_public_data
from .graph import symbol_graph
from .knowledge import add_behaviour_steering
from .knowledge import get_knowledge
from .knowledge import store_knowledge
from .parallel import notebook_locks
from .read import nb_cell
from .read import nb_chapter
from .read import nb_overview
from .read import show_doc

# %% ../nbs/07_mcp.ipynb #mcpimports5
from .review import reset_global_usage_summary
from .review import notebook_size_problems
from .review import notebook_validation_problems
from .review import public_function_literacy_problems
from .review import run_style_check
from .review import style_check
from .review import style_report
from .review import diff_nb
from .write import apply_notebook_edit
from .write import insert_notebook_cells
from .write import replace_notebook_cell
from .write import replace_notebook_range
from .write import should_run_cell_feedback
from .write import source_lines_cells

# %% ../nbs/07_mcp.ipynb #eea5a32c
def as_text(value):
    return "" if value is None else str(value)

# %% ../nbs/07_mcp.ipynb #280b52f0
_CAPTURE_LOCK = threading.RLock()

# %% ../nbs/07_mcp.ipynb #54bed38d
_REDACT_KEYS = {"new", "new_lines", "source_lines", "replacement_lines", "cells", "edits", "operations", "source", "old_str", "new_str"}

# %% ../nbs/07_mcp.ipynb #17643142
_REMOVED_SCRIPT_NAMES = (
    "nbskill-mcp", "read-nb", "write-nb", "update-cell", "batch-edit-nb",
    "show-doc", "exec-nb", "diff-nb", "style-check", "symbol-graph", "private-symbol-report",
)

# %% ../nbs/07_mcp.ipynb #e1c063ce
def _package_version(name="nbskill"):
    try: return version(name)
    except PackageNotFoundError: return "unknown"

# %% ../nbs/07_mcp.ipynb #c9b5a958
def capture_call(func, **kwargs):
    out, err = StringIO(), StringIO()
    with _CAPTURE_LOCK:
        original_stdout, original_stderr = sys.stdout, sys.stderr
        try:
            try:
                with redirect_stdout(out), redirect_stderr(err):
                    result = func(**kwargs)
            except SystemExit as exc:
                chunks = []
                if out.getvalue(): chunks.append(out.getvalue().rstrip())
                if err.getvalue(): chunks.append(err.getvalue().rstrip())
                chunks.append(f"SystemExit: {exc.code}")
                raise RuntimeError(chr(10).join(chunk for chunk in chunks if chunk)) from exc
        finally:
            sys.stdout, sys.stderr = original_stdout, original_stderr
    chunks = []
    if out.getvalue(): chunks.append(out.getvalue().rstrip())
    if err.getvalue(): chunks.append(err.getvalue().rstrip())
    if result is not None and not chunks: chunks.append(as_text(result))
    return chr(10).join(chunk for chunk in chunks if chunk)

# %% ../nbs/07_mcp.ipynb #81ba4476
def capture_notebook_call(func, *paths, **kwargs):
    "Capture a call while holding per-notebook locks for `paths`."
    with notebook_locks(*paths):
        return capture_call(func, **kwargs)

# %% ../nbs/07_mcp.ipynb #aca48286
def _mcp_find_cell(path, cell_id):
    nb = _read_raw_nb(path)
    for cell in nb.cells:
        if getattr(cell, "id", None) == cell_id: return cell
    raise ValueError(f"Cell id {cell_id!r} was not found in {path}")

# %% ../nbs/07_mcp.ipynb #e190c674
def _mcp_source_hash(source):
    return hashlib.sha256(str(source).encode("utf-8")).hexdigest()[:12]

# %% ../nbs/07_mcp.ipynb #edb5273c
def _mcp_cell_source_hash(path, cell_id):
    return _mcp_source_hash(cell_source(_mcp_find_cell(path, cell_id)))

# %% ../nbs/07_mcp.ipynb #e13bac02
def _mcp_expected_hash_warning(path, cell_id, expected_hash):
    if not expected_hash: return None
    actual = _mcp_cell_source_hash(path, cell_id)
    if actual == expected_hash: return None
    return _warning(
        "expected_hash_mismatch",
        f"Skipped edit for {path} id={cell_id}: expected hash {expected_hash}, found {actual}.",
        "Refresh nb_cell context and retry with the current source.",
        path=str(path), cell_id=cell_id, expected_hash=expected_hash, actual_hash=actual,
    )

# %% ../nbs/07_mcp.ipynb #da137c83
def _capture_exec_nb_cli_call(arguments):
    call_args = {key: value for key, value in arguments.items() if key != "detail"}
    script = "; ".join([
        "import json, sys",
        "from nbskill.execute import exec_nb",
        "exec_nb(**json.loads(sys.argv[1]))",
    ])
    lock_paths = [call_args.get("path")]
    if call_args.get("dest"): lock_paths.append(call_args["dest"])
    with notebook_locks(*lock_paths):
        proc = subprocess.run(
            [sys.executable, "-c", script, json.dumps(call_args)],
            text=True, capture_output=True, cwd=str(Path.cwd()),
        )
    chunks = [item.rstrip() for item in (proc.stdout, proc.stderr) if item]
    output = chr(10).join(chunks)
    if proc.returncode != 0:
        raise RuntimeError(output or f"exec_nb subprocess failed with exit code {proc.returncode}")
    return output

# %% ../nbs/07_mcp.ipynb #92b5d9b5
def _mcp_cell_index(path, cell_id):
    nb = _read_raw_nb(path)
    for index, cell in enumerate(nb.cells):
        if getattr(cell, "id", None) == cell_id: return index
    raise ValueError(f"Cell id {cell_id!r} was not found in {path}")

# %% ../nbs/07_mcp.ipynb #139c6c5a
def _mcp_cell_ids_from_index(path, start, count):
    if start is None or count <= 0: return []
    nb = _read_raw_nb(path)
    return [
        getattr(cell, "id", None) for cell in nb.cells[start:start + count]
        if getattr(cell, "id", None)
    ]

# %% ../nbs/07_mcp.ipynb #bfc3af9b
def _mcp_structured_cell_count(cells, default_cell_type="code"):
    return sum(len(source_lines_cells(cell, default_cell_type)) for cell in (cells or []))

# %% ../nbs/07_mcp.ipynb #27561ec6
def _mcp_feedback_location(path, edit, default_cell_type="code"):
    edit_path = str(edit.get("path") or path)
    op = edit.get("op")
    if op == "replace_cell":
        cell_id = edit.get("cell_id")
        return edit_path, _mcp_cell_index(edit_path, cell_id), _mcp_structured_cell_count([edit], default_cell_type)
    if op == "replace_range":
        return edit_path, _mcp_cell_index(edit_path, edit.get("cell_id")), 1
    if op in {"insert_before", "insert_after"}:
        anchor_id = edit.get("anchor_id") or edit.get("cell_id")
        anchor_index = _mcp_cell_index(edit_path, anchor_id)
        start = anchor_index if op == "insert_before" else anchor_index + 1
        return edit_path, start, _mcp_structured_cell_count(edit.get("cells") or [edit], default_cell_type)
    return edit_path, None, 0

# %% ../nbs/07_mcp.ipynb #7c1eac0d
def _mcp_feedback_output(path, cell_ids, auto_feedback=True, feedback_timeout=10, feedback_safe=True):
    if not auto_feedback: return ""
    nb = _read_raw_nb(path)
    cells_by_id = {getattr(cell, "id", None): cell for cell in nb.cells}
    target_id = None
    for cell_id in cell_ids:
        cell = cells_by_id.get(cell_id)
        if cell is not None and should_run_cell_feedback(cell): target_id = cell_id
    if target_id is None: return ""
    output = _capture_exec_nb_cli_call(dict(
        path=str(path), dest=None, exc_stop=False, up2id=target_id, chapter=None,
        timeout=feedback_timeout, show_output=True, verbose=False, safe=feedback_safe,
        allow=None, ok_dests=None, cache_httpx=False, cache_dir=None,
        cache_domains=None, allow_new=True, check_only=True,
    ))
    return f"Auto feedback (up to id={target_id}):\n{output}".rstrip()

# %% ../nbs/07_mcp.ipynb #56bbc791
def _append_mcp_feedback(message, path, cell_ids, auto_feedback=True, feedback_timeout=10, feedback_safe=True):
    feedback = _mcp_feedback_output(path, cell_ids, auto_feedback, feedback_timeout, feedback_safe)
    return "\n\n".join(chunk for chunk in [message.rstrip(), feedback] if chunk)

# %% ../nbs/07_mcp.ipynb #fca505e1
def _json_preview(value, limit=1200):
    text = json.dumps(value, indent=2, sort_keys=True, default=str)
    if len(text) <= limit: return text
    return f"{text[:limit].rstrip()}\n... truncated ..."

# %% ../nbs/07_mcp.ipynb #0b415b43
def _text_preview(value, limit=12000):
    text = as_text(value)
    if limit is None or len(text) <= limit:
        return {"text": text, "truncated": False, "chars": len(text), "omitted_chars": 0}
    omitted = len(text) - limit
    return {
        "text": f"{text[:limit].rstrip()}\n... truncated {omitted} chars ...",
        "truncated": True,
        "chars": len(text),
        "omitted_chars": omitted,
    }

# %% ../nbs/07_mcp.ipynb #eb6a3482
def _redact_value(key, value, limit=160):
    if value is None: return None
    text = as_text(value)
    if key in _REDACT_KEYS and len(text) > limit:
        return f"<{len(text)} chars redacted; use detail='debug' to inspect>"
    if len(text) > limit * 3:
        return f"{text[:limit].rstrip()}... <{len(text) - limit} more chars>"
    return value

# %% ../nbs/07_mcp.ipynb #85f63aa6
def _redact_arguments(arguments):
    return {key: _redact_value(key, value) for key, value in (arguments or {}).items()}

# %% ../nbs/07_mcp.ipynb #59c01424
def _warning(code, message, next_action=None, **extra):
    item = {"code": code, "message": message}
    if next_action: item["next_action"] = next_action
    item.update({key: value for key, value in extra.items() if value is not None})
    return item

# %% ../nbs/07_mcp.ipynb #268cfbcf
def _path_without_cwd_prefix(path):
    return path_candidates(path)[-1]

# %% ../nbs/07_mcp.ipynb #f3c16e1b
def _git_base(path="."):
    base = _path_without_cwd_prefix(path)
    if (base.exists() and not base.is_dir()) or (not base.exists() and base.suffix):
        return base.parent
    return base

# %% ../nbs/07_mcp.ipynb #2f499bc7
def _rooted_path(path, root):
    raw = Path(str(path)).expanduser()
    pth = _path_without_cwd_prefix(path)
    candidates = [pth]
    if root is not None and not raw.is_absolute():
        candidates = [Path(root) / raw, Path(root) / pth, *candidates]
    for candidate in candidates:
        try:
            if candidate.exists(): return candidate.resolve()
        except OSError:
            continue
    return pth.resolve()

# %% ../nbs/07_mcp.ipynb #919caf72
def _rel_to_root(path, root):
    try: return _rooted_path(path, root).relative_to(Path(root).resolve()).as_posix()
    except (OSError, ValueError): return str(path)

# %% ../nbs/07_mcp.ipynb #31b8ef72
def _generated_files(root):
    skip = {".git", ".venv", "__pycache__", ".mypy_cache", ".pytest_cache"}
    items = []
    for path in Path(root).rglob("*.py"):
        if any(part in skip for part in path.parts): continue
        owner = generated_owner(path)
        if owner is not None: items.append((path, owner))
    return items

# %% ../nbs/07_mcp.ipynb #6bcff7cc
def _owner_output(path):
    owner = generated_owner(path)
    if owner is None: return f"No generated-notebook owner found for {path}"
    return f"Generated file owner: {path} -> {owner}"

# %% ../nbs/07_mcp.ipynb #84acf4e8
def _failure_data():
    path = failure_map_path()
    try: return load_failure_map(path) if path.exists() else empty_failure_map()
    except OSError: return empty_failure_map()

# %% ../nbs/07_mcp.ipynb #acc0b7ac
def _resolve_diagnostic_scope(path, root, scope_path=None):
    raw = path if scope_path in (None, "") else scope_path
    if raw in (None, "", "."): return Path(root)
    scoped = Path(raw).expanduser()
    if not scoped.is_absolute(): scoped = Path(root) / scoped
    return scoped

# %% ../nbs/07_mcp.ipynb #3f498989
def _is_project_scope(path, root):
    try: return Path(path).resolve() == Path(root).resolve()
    except OSError: return False

# %% ../nbs/07_mcp.ipynb #342e2c42
def _generated_pairs_for_scope(root, path):
    path = Path(path)
    if _is_project_scope(path, root): return _generated_files(root)
    if path.suffix == ".py":
        owner = generated_owner(path)
        return [(path, owner)] if owner is not None else []
    pairs = []
    for nb_path in notebook_paths(path):
        try: py_path = exported_py_path(nb_path)
        except (FileNotFoundError, OSError): py_path = None
        if py_path is not None and Path(py_path).exists(): pairs.append((Path(py_path), nb_path.resolve()))
    return pairs

# %% ../nbs/07_mcp.ipynb #dfcb6cd7
def _cell_source_text(cell):
    if isinstance(cell, dict):
        source = cell.get("source", "")
        return "".join(source) if isinstance(source, list) else str(source)
    return cell_source(cell)

# %% ../nbs/07_mcp.ipynb #ebe7ca04
def _cell_type_text(cell):
    return cell.get("cell_type", "") if isinstance(cell, dict) else getattr(cell, "cell_type", "")

# %% ../nbs/07_mcp.ipynb #4ed2de30
def _cell_export_relevant(cell):
    if _cell_type_text(cell) != "code": return False
    return any(re.match(r"^\s*#\|\s*(export|default_exp)\b", line) for line in _cell_source_text(cell).splitlines())

# %% ../nbs/07_mcp.ipynb #d03534e0
def _notebook_export_relevant_change(owner, root):
    owner = Path(owner)
    root = Path(root)
    owner_rel = _rel_to_root(owner, root)
    proc = subprocess.run(["git", "-C", str(root), "show", f"HEAD:{owner_rel}"], text=True, capture_output=True)
    if proc.returncode != 0: return True
    try:
        old_nb = json.loads(proc.stdout)
        new_nb = json.loads(owner.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return True
    old_cells = {cell.get("id"): cell for cell in old_nb.get("cells", []) if cell.get("id")}
    new_cells = {cell.get("id"): cell for cell in new_nb.get("cells", []) if cell.get("id")}
    for cell_id in set(old_cells) | set(new_cells):
        old_cell, new_cell = old_cells.get(cell_id), new_cells.get(cell_id)
        if old_cell is None or new_cell is None:
            changed = True
        else:
            changed = _cell_type_text(old_cell) != _cell_type_text(new_cell) or _cell_source_text(old_cell) != _cell_source_text(new_cell)
        if changed and any(_cell_export_relevant(cell) for cell in (old_cell, new_cell) if cell is not None):
            return True
    return False

# %% ../nbs/07_mcp.ipynb #02a83d8a
def _style_problem_warnings(path, root):
    warnings = []
    problems = [*notebook_size_problems(path), *public_function_literacy_problems(path)]
    for problem in problems:
        code = problem.get("code")
        if code == "large-cell":
            cell = f" cell id={problem['cell_id']}" if problem.get("cell_id") else ""
            warnings.append(_warning(
                "large_cell",
                f"Notebook {_rel_to_root(problem.get('path'), root)}{cell} is large: {problem.get('detail')}.",
                "Split the cell so it contains one idea before continuing.",
                path=problem.get("path"), cell_id=problem.get("cell_id"), problem=problem,
            ))
        elif code == "large-generated-py":
            generated = problem.get("exported_py_path")
            warnings.append(_warning(
                "large_generated_py",
                f"Generated file {_rel_to_root(generated, root)} is getting large: {problem.get('detail')}.",
                "Use the notebook split tool to split the source notebook/module.",
                path=problem.get("path"), generated=generated, problem=problem,
            ))
        elif str(code).startswith("public-function-"):
            missing = problem.get("missing") or "one-line docstring"
            symbol = problem.get("symbol", "<unknown>")
            warnings.append(_warning(
                code.replace("-", "_"),
                f"Notebook {_rel_to_root(problem.get('path'), root)} public function {symbol!r} is missing {missing}.",
                "Add Markdown docs, a one-line docstring, an example cell, and a focused test cell.",
                path=problem.get("path"), cell_id=problem.get("cell_id"), problem=problem,
            ))
    return warnings

# %% ../nbs/07_mcp.ipynb #726391c2
def _warning_scope_root_rel(path, root):
    if path in (None, ""): return ""
    try:
        return Path(path).expanduser().resolve().relative_to(Path(root).resolve()).as_posix()
    except (OSError, ValueError):
        return str(path).strip()

# %% ../nbs/07_mcp.ipynb #0e221723
def _warning_scope_matches(value, root, scope):
    if scope is None: return True
    rel = _warning_scope_root_rel(value, root)
    return any(rel == item or rel.startswith(f"{item.rstrip('/')}/") for item in scope)

# %% ../nbs/07_mcp.ipynb #9af4f282
def _warning_related_paths(item):
    for key in ("path", "generated", "owner"):
        if item.get(key): yield item[key]
    problem = item.get("problem") or {}
    for key in ("path", "exported_py_path"):
        if problem.get(key): yield problem[key]

# %% ../nbs/07_mcp.ipynb #5935eda4
def _warning_cell_id(item):
    problem = item.get("problem") or {}
    return item.get("cell_id") or problem.get("cell_id")

# %% ../nbs/07_mcp.ipynb #60aef7b3
_NOTEBOOK_LEVEL_CONTEXT_WARNING_CODES = {
    "generated_without_notebook", "notebook_export_missing", "exported_py_hash_mismatch",
}

# %% ../nbs/07_mcp.ipynb #c995706f
def _filter_warnings_for_scope(warnings, root, scope_path=None, scope_cell_ids=None):
    if scope_path in (None, "", ".") and scope_cell_ids is None: return warnings
    scope = None if scope_path in (None, "", ".") else {_warning_scope_root_rel(scope_path, root).rstrip("/")}
    cell_filter_active = scope_cell_ids is not None
    cell_ids = set(scope_cell_ids or [])
    filtered = []
    for item in warnings:
        if scope is not None and not any(_warning_scope_matches(path, root, scope) for path in _warning_related_paths(item)):
            continue
        cell_id = _warning_cell_id(item)
        if cell_filter_active and cell_id and cell_id not in cell_ids: continue
        if cell_filter_active and not cell_id and item.get("code") not in _NOTEBOOK_LEVEL_CONTEXT_WARNING_CODES: continue
        filtered.append(item)
    return filtered

# %% ../nbs/07_mcp.ipynb #c4de68df
def _doctor_warnings(path=".", scope_path=None, scope_cell_ids=None):
    root = git_root(path) or _git_base(path).resolve()
    diagnostic_path = _resolve_diagnostic_scope(path, root, scope_path)
    project_scope = _is_project_scope(diagnostic_path, root)
    changed = git_status_paths(root) if (root / ".git").exists() else set()
    warnings = []
    for py_path, owner in _generated_pairs_for_scope(root, diagnostic_path):
        py_rel = _rel_to_root(py_path, root)
        owner_rel = _rel_to_root(owner, root)
        if py_rel in changed and owner_rel not in changed:
            warnings.append(_warning(
                "generated_without_notebook",
                f"Generated file {py_rel} changed without its source notebook {owner_rel}.",
                "Move the edit into the notebook and export, or verify the generated edit is intentional.",
                path=py_rel, owner=owner_rel,
            ))
        if owner_rel in changed and py_rel not in changed:
            if _notebook_export_relevant_change(owner, root):
                warnings.append(_warning(
                    "notebook_export_missing",
                    f"Notebook {owner_rel} changed but generated file {py_rel} is unchanged.",
                    "Run export or use an nbskill write tool before shipping.",
                    path=owner_rel, generated=py_rel,
                ))
    for problem in notebook_validation_problems(diagnostic_path):
        if problem.get("code") != "exported-py-hash-mismatch": continue
        warnings.append(_warning(
            "exported_py_hash_mismatch",
            f"Notebook {problem['path']} metadata does not match current generated file {problem.get('exported_py_path')}.",
            "Run nbskill_validate or export the notebook through nbskill write tools.",
            path=problem.get("path"), generated=problem.get("exported_py_path"),
        ))
    warnings.extend(_style_problem_warnings(diagnostic_path, root))
    if project_scope:
        warnings.extend(_doc_script_warnings(root))
        failures = _failure_data().get("events", [])[-10:]
        recent_failures = [event for event in failures if event.get("kind") == "failure"]
        if recent_failures:
            last = recent_failures[-1]
            warnings.append(_warning(
                "recent_tool_failures",
                f"Recent nbskill failure: {last.get('tool')} {last.get('summary') or last.get('error')}",
                "Run doctor(detail='debug') or style_check(delete_after_output=True) after resolving it.",
                tool=last.get("tool"),
            ))
    if scope_path is None: scope_path = path
    return _filter_warnings_for_scope(warnings, root, scope_path, scope_cell_ids)

# %% ../nbs/07_mcp.ipynb #0e3ba43b
def _doc_script_warnings(root):
    docs = [Path(root) / "README.md", Path(root) / "nbskill" / "SKILL.md"]
    docs += list((Path(root) / "nbskill" / "references").glob("*.md")) if (Path(root) / "nbskill" / "references").exists() else []
    warnings = []
    for doc in docs:
        if not doc.exists(): continue
        try: text = doc.read_text(encoding="utf-8", errors="ignore")
        except OSError: continue
        found = sorted(name for name in _REMOVED_SCRIPT_NAMES if name in text)
        if found:
            warnings.append(_warning(
                "removed_script_name",
                f"{doc.relative_to(root)} references removed CLI names: {', '.join(found)}.",
                "Replace hyphenated command names with underscore script names.",
                path=str(doc), names=found,
            ))
    return warnings

# %% ../nbs/07_mcp.ipynb #41f6c634
def _first_match(pattern, text, flags=0):
    match = re.search(pattern, text or "", flags)
    return match.group(1) if match else None

# %% ../nbs/07_mcp.ipynb #b14208e2
def _line_cell_ids(text):
    return set(re.findall(r"^Cell id=([^\s:]+)", text or "", re.MULTILINE))

# %% ../nbs/07_mcp.ipynb #928582a3
def _response_scope_cell_ids(tool, arguments, preview):
    text = preview.get("text", "")
    if tool == "nb_overview": return None
    if tool == "nb_chapter": return _line_cell_ids(text) or None
    if tool == "nb_cell":
        if arguments.get("id"): return {str(arguments["id"])}
        cell_id = _first_match(r"^Cell id=([^\s:]+)", text, re.MULTILINE)
        return {cell_id} if cell_id else None
    if tool == "show_doc":
        cell_id = _first_match(r"^Location:.*?Cell id=([^\s:]+)", text, re.MULTILINE)
        return {cell_id} if cell_id else None
    if tool == "diff_nb":
        ids = set(re.findall(r"--- code cell ([^\s]+) ---", text))
        return ids if ids else set()
    if tool in {"edit_cell", "edit_cell_range"}:
        cell_id = arguments.get("cell_id") or _first_match(r"Updated .* id=([^\s]+)", text)
        return {str(cell_id)} if cell_id else None
    if tool == "insert_cells":
        anchor_id = arguments.get("anchor_id")
        return {str(anchor_id)} if anchor_id else None
    if tool == "apply_notebook_edits":
        ids = {str(item.get("cell_id") or item.get("anchor_id")) for item in arguments.get("edits", []) if isinstance(item, dict) and (item.get("cell_id") or item.get("anchor_id"))}
        return ids or None
    if tool == "exec_nb":
        up2id = arguments.get("up2id")
        if isinstance(up2id, str) and up2id and not up2id.isdigit(): return {up2id}
        return _line_cell_ids(text) or None
    for key in ("id", "cell_id", "any_cell_id"):
        value = arguments.get(key)
        if value: return {str(value)}
    return None

# %% ../nbs/07_mcp.ipynb #c8b5469d
def _unique_strings(items):
    seen, result = set(), []
    for item in items:
        if item in seen: continue
        seen.add(item)
        result.append(item)
    return result

# %% ../nbs/07_mcp.ipynb #362e0a70
def _notebook_paths_from_text(text):
    return _unique_strings(re.findall(r"(?<![\w.-])(?:[~./A-Za-z0-9_-]+\.ipynb)", text or ""))

# %% ../nbs/07_mcp.ipynb #dffc637d
def _edit_scope_paths(arguments):
    default = arguments.get("path")
    edits = arguments.get("edits") or []
    paths = [default] if default else []
    paths += [item.get("path") for item in edits if isinstance(item, dict) and item.get("path")]
    return _unique_strings(str(item) for item in paths if item)

# %% ../nbs/07_mcp.ipynb #7645304f
def _response_scope_paths(tool, arguments, preview):
    text_paths = _notebook_paths_from_text(preview.get("text", ""))
    if tool == "apply_notebook_edits":
        return _unique_strings([*_edit_scope_paths(arguments), *text_paths])
    if tool in {"edit_cell", "edit_cell_range", "insert_cells"} and text_paths:
        return text_paths
    path = arguments.get("path") or arguments.get("nb_path")
    return [str(path)] if path else []

# %% ../nbs/07_mcp.ipynb #8bab5b6e
def _dedupe_warnings(warnings):
    seen, result = set(), []
    for item in warnings:
        key = json.dumps(item, sort_keys=True, default=str)
        if key in seen: continue
        seen.add(key)
        result.append(item)
    return result

# %% ../nbs/07_mcp.ipynb #420b6fc4
def _response_warnings(tool, arguments, preview):
    warnings = []
    if preview.get("truncated"):
        warnings.append(_warning(
            "output_truncated",
            f"{tool} output was truncated by {preview['omitted_chars']} chars.",
            "Repeat with a narrower query or detail='debug' if you need full context.",
        ))
    context_tools = {"nb_overview", "nb_chapter", "nb_cell", "show_doc", "diff_nb"}
    scoped_project_tools = {"edit_cell", "edit_cell_range", "insert_cells", "apply_notebook_edits", "exec_nb"}
    if tool in context_tools:
        path = arguments.get("path") or arguments.get("nb_path") or "."
        cell_ids = _response_scope_cell_ids(tool, arguments, preview)
        warnings.extend(_doctor_warnings(path, scope_path=path, scope_cell_ids=cell_ids)[:3])
    elif tool in scoped_project_tools:
        cell_ids = _response_scope_cell_ids(tool, arguments, preview)
        for path in _response_scope_paths(tool, arguments, preview):
            warnings.extend(_doctor_warnings(path, scope_path=path, scope_cell_ids=cell_ids))
    return _dedupe_warnings(warnings)[:3]

# %% ../nbs/07_mcp.ipynb #4a32f9e9
def _brief_call(tool, arguments, preview):
    lines = [f"{tool} completed"]
    for key in ("path", "nb_path", "cell_id", "id", "chapter", "name", "any_cell_id", "symbol"):
        if arguments.get(key) not in (None, ""):
            lines.append(f"{key}={arguments[key]}")
    if arguments.get("dry_run") is True: lines.append("dry_run=True")
    if preview.get("truncated"): lines.append(f"output_truncated=True omitted_chars={preview['omitted_chars']}")
    return lines

# %% ../nbs/07_mcp.ipynb #efed7008
def mcp_tool_result(tool, arguments, full_output, max_output_chars=12000, detail="summary", warnings=None, hints=None, **structured):
    "Return concise visible MCP text plus structured data for clients that inspect it."
    detail = detail or "summary"
    preview = _text_preview(full_output or "", limit=max_output_chars)
    warnings = _dedupe_warnings([*(warnings or []), *_response_warnings(tool, arguments or {}, preview)])
    hints = list(hints or [])
    lines = _brief_call(tool, arguments or {}, preview)
    if preview["text"]:
        lines += ["", "Result:", preview["text"]]
    if warnings:
        lines += ["", "Warnings:"]
        lines.extend(f"- {item['message']}" + (f" Next: {item['next_action']}" if item.get("next_action") else "") for item in warnings)
    if detail == "debug" and hints:
        lines += ["", "Hints:"]
        lines.extend(f"- {hint}" for hint in hints)
    summary = "\n".join(lines)
    data = {
        "summary": summary,
        "call": {"tool": tool, "arguments": _redact_arguments(arguments or {})},
        "full_output": preview["text"],
        "output_truncated": preview["truncated"],
        "output_chars": preview["chars"],
        "omitted_chars": preview["omitted_chars"],
        "warnings": warnings,
        "hints": hints if detail == "debug" else [],
    }
    if detail == "debug":
        data["debug"] = {"arguments": arguments or {}, "raw_output": as_text(full_output or "")}
    data.update(structured)
    return ToolResult(content=[TextContent(type="text", text=summary)], structured_content=data)

# %% ../nbs/07_mcp.ipynb #d696afd1
def _status_data():
    scripts = [
        "nb_overview", "nb_chapter", "nb_cell", "write_nb", "update_cell",
        "batch_edit_nb", "show_doc", "exec_nb", "diff_nb", "style_check",
        "install_nbskill", "symbol_graph", "private_symbol_report", "agent_workbench",
        "new_nbdev_notebook", "add_behaviour_steering", "store_knowledge", "get_knowledge",
        "nbskill_mcp",
    ]
    return {
        "version": _package_version(),
        "cwd": str(Path.cwd()),
        "python": sys.executable,
        "mcp_command": "nbskill_mcp",
        "mcp_command_path": shutil.which("nbskill_mcp"),
        "cli_tools": {name: shutil.which(name) for name in scripts},
        "reconnect_hint": "Restart or reconnect the MCP client after reinstalling nbskill or changing tool signatures.",
        "install_commands": [
            "uv tool install --editable . --force",
            "codex mcp add nbskill -- nbskill_mcp",
            "claude mcp add nbskill -- nbskill_mcp",
        ],
    }

# %% ../nbs/07_mcp.ipynb #7a5dcc61
def _doctor_report(
    path=".",
    detail="summary",
    fix=False,
    reset=False,
    capabilities="",
    scopes="error,warning",
    skip_folder_re=None,
    skip_path=None,
    max_output_chars=12000,
    max_diagnostics=200,
):
    root = git_root(path) or _git_base(path).resolve()
    status = _status_data()
    selected = _doctor_scope_set(scopes)
    errors = _doctor_error_items(path, status) if "error" in selected else []
    warnings, private_text = _doctor_warning_items(path) if "warning" in selected else ([], "")
    style = (
        _doctor_style_report(path, skip_folder_re=skip_folder_re, skip_path=skip_path, max_output_chars=max_output_chars, max_diagnostics=max_diagnostics)
        if "style" in selected else None
    )
    failure_map = _failure_data()
    if reset: reset_global_usage_summary()
    hints = [
        "Use scopes='error,warning,style' or scopes='all' for the full doctor report.",
        "Use scopes='style' to include chkstyle output; chkstyle is omitted from error/warning scopes.",
        "Use nb_overview/nb_chapter/nb_cell/show_doc, then edit_cell, edit_cell_range, insert_cells, or apply_notebook_edits.",
    ]
    changed = sorted(git_status_paths(root)) if (root / ".git").exists() else []
    generated = [
        {"path": _rel_to_root(py, root), "owner": _rel_to_root(owner, root)}
        for py, owner in _generated_files(root)
    ]
    issue_count = len(errors) + len(warnings)
    style_count = (style or {}).get("summary", {}).get("diagnostic_count", 0)
    summary = f"nbskill doctor: {len(errors)} error(s), {len(warnings)} warning(s)"
    if "style" in selected: summary += f", {style_count} style diagnostic(s)"
    if not issue_count and "style" not in selected: summary = "nbskill doctor: no actionable errors or warnings"
    text_lines = [summary]
    if errors:
        text_lines.append("\nErrors:")
        text_lines.extend(f"- {item['message']}" + (f" Next: {item['next_action']}" if item.get("next_action") else "") for item in errors)
    if warnings:
        text_lines.append("\nWarnings:")
        text_lines.extend(f"- {item['message']}" + (f" Next: {item['next_action']}" if item.get("next_action") else "") for item in warnings)
    if style is not None and style.get("text", "").strip():
        text_lines.append("\nStyle:")
        text_lines.append(style["text"].strip())
    report = {
        "path": str(path),
        "root": str(root),
        "scopes": sorted(selected),
        "status": status,
        "errors": errors,
        "warnings": warnings,
        "issues": [*errors, *warnings],
        "style": style,
        "private_symbol_report": private_text if "warning" in selected else "",
        "hints": hints,
        "capabilities": [item for item in _MCP_CAPABILITIES.split(",") if item],
        "changed_paths": changed if detail == "debug" else changed[:20],
        "generated_owners": generated if detail == "debug" else generated[:20],
        "recent_events": failure_map.get("events", [])[-20:] if detail == "debug" else [],
        "counts": failure_map.get("counts", {}),
        "reset": bool(reset),
        "fix": {"requested": bool(fix), "applied": []},
        "text": "\n".join(text_lines),
    }
    return report

# %% ../nbs/07_mcp.ipynb #85b62f4f
def nbskill_status(json_output: bool = False):  # Keep argument for compatibility with the CLI wrapper
    "Report nbskill version, MCP command setup, canonical CLI tools, and reconnect hints."
    return _status_data()

# %% ../nbs/07_mcp.ipynb #0bae0134
_DOCTOR_SCOPES = {"error", "warning", "style"}

# %% ../nbs/07_mcp.ipynb #f96ad58c
def _doctor_scope_set(scopes="error,warning"):
    "Normalize comma/space-separated doctor scopes."
    if scopes is None: return {"error", "warning"}
    raw = str(scopes).replace(",", " ").split()
    selected = set(raw) or {"error", "warning"}
    if "all" in selected: return set(_DOCTOR_SCOPES)
    unknown = selected - _DOCTOR_SCOPES
    if unknown: raise ValueError(f"Unknown doctor scope(s): {', '.join(sorted(unknown))}")
    return selected

# %% ../nbs/07_mcp.ipynb #a9fdf5ae
def _problem_message(problem):
    parts = [str(problem.get("path") or "")]
    if problem.get("cell_id"): parts.append(f"id={problem['cell_id']}")
    if problem.get("line"): parts.append(f"line={problem['line']}")
    if problem.get("symbol"): parts.append(f"symbol={problem['symbol']!r}")
    if problem.get("code"): parts.append(f"code={problem['code']}")
    if problem.get("detail"): parts.append(str(problem["detail"]))
    return " ".join(part for part in parts if part)

# %% ../nbs/07_mcp.ipynb #b41ba96e
def _doctor_validation_errors(path):
    errors = []
    for problem in notebook_validation_problems(path):
        errors.append(_warning(
            problem.get("code", "notebook-validation"),
            _problem_message(problem),
            "Fix notebook metadata/source ordering before relying on notebook edits.",
            severity="error", scope="error", problem=problem,
        ))
    return errors

# %% ../nbs/07_mcp.ipynb #43f8a5cc
def _doctor_order_errors(path):
    errors = []
    try:
        problems = notebook_order_problems(path)
    except FileNotFoundError as exc:
        return [_warning(
            "notebook_order_missing_file",
            f"Notebook order scan found a missing notebook: {exc.filename or exc}",
            "Remove stale notebook references or recreate the missing notebook before rerunning doctor.",
            severity="error", scope="error", path=exc.filename,
        )]
    for problem in problems:
        errors.append(_warning(
            problem.get("code", "notebook-order"),
            _problem_message(problem),
            "Move definitions/imports before use, or add the missing import.",
            severity="error", scope="error", problem=problem,
        ))
    return errors

# %% ../nbs/07_mcp.ipynb #11df0ec4
def _doctor_recent_failure_errors():
    errors = []
    recent = [event for event in _failure_data().get("events", [])[-10:] if event.get("kind") == "failure"]
    if recent:
        last = recent[-1]
        errors.append(_warning(
            "recent_tool_failures",
            f"Recent nbskill failure: {last.get('tool')} {last.get('summary') or last.get('error')}",
            "Run doctor(detail='debug', scopes='error') after resolving it.",
            severity="error", scope="error", tool=last.get("tool"),
        ))
    return errors

# %% ../nbs/07_mcp.ipynb #d7eeec10
def _doctor_error_items(path, status):
    errors = [
        *_doctor_validation_errors(path),
        *_doctor_order_errors(path),
        *_doctor_recent_failure_errors(),
    ]
    if not status.get("mcp_command_path"):
        errors.append(_warning(
            "mcp_command_missing",
            "nbskill_mcp is not on PATH for this process.",
            "Run uv tool install --editable . --force and reconnect the MCP client.",
            severity="error", scope="error",
        ))
    return errors

# %% ../nbs/07_mcp.ipynb #5c694b38
def _private_symbol_report_text(path):
    return capture_call(private_symbol_report, path=str(path))

# %% ../nbs/07_mcp.ipynb #ef084d22
def _private_symbol_warnings(path):
    try:
        text = _private_symbol_report_text(path)
    except FileNotFoundError as exc:
        text = f"Private symbol scan found a missing notebook: {exc.filename or exc}"
        return [_warning(
            "private_symbol_missing_file",
            text,
            "Remove stale notebook references or recreate the missing notebook before rerunning doctor.",
            severity="warning", scope="warning", path=exc.filename,
        )], text
    if "No cross-notebook private symbol calls found." in text:
        return [], text
    warnings = [
        _warning(
            "private_symbol_call",
            line[2:],
            "Promote the helper to public API or keep the call inside the defining notebook.",
            severity="warning", scope="warning",
        )
        for line in text.splitlines()
        if line.startswith("- ")
    ]
    return warnings, text

# %% ../nbs/07_mcp.ipynb #44b0f45c
def _doctor_warning_items(path):
    error_codes = {"exported_py_hash_mismatch", "recent_tool_failures"}
    warnings = [
        {**item, "severity": item.get("severity", "warning"), "scope": "warning"}
        for item in _doctor_warnings(path)
        if item.get("code") not in error_codes
    ]
    private_warnings, private_text = _private_symbol_warnings(path)
    return [*warnings, *private_warnings], private_text

# %% ../nbs/07_mcp.ipynb #a6dc04e5
def _doctor_style_report(path, skip_folder_re=None, skip_path=None, max_output_chars=12000, max_diagnostics=200):
    chkstyle = run_style_check(path, skip_folder_re, skip_path, strict=False, max_output_chars=max_output_chars)
    try:
        return style_report(
            path, chkstyle=chkstyle, max_output_chars=max_output_chars,
            max_diagnostics=max_diagnostics, skip_folder_re=skip_folder_re, skip_path=skip_path,
        )
    except FileNotFoundError as exc:
        message = f"Style scan found a missing notebook: {exc.filename or exc}"
        diagnostic = {
            "source": "notebook",
            "code": "style_missing_file",
            "severity": "error",
            "path": exc.filename,
            "detail": message,
        }
        output = chkstyle.get("output", "") if isinstance(chkstyle, dict) else ""
        truncated = max_output_chars is not None and len(output) > max_output_chars
        text = output[:max_output_chars].rstrip() if truncated else output.strip()
        if text: text = f"{text}\n\n{message}"
        else: text = message
        return {
            "path": str(path),
            "summary": {
                "notebook_problem_count": 1,
                "chkstyle_problem_count": 0,
                "diagnostic_count": 1,
                "recent_problem_count": 0,
                "output_truncated": truncated,
                "output_chars": len(output),
                "omitted_chars": max(0, len(output) - (max_output_chars or len(output))),
            },
            "diagnostics": [diagnostic],
            "problem_chart": {
                "by_code": {"style_missing_file": 1},
                "by_severity": {"error": 1},
                "by_path": {str(exc.filename): 1} if exc.filename else {},
                "by_source": {"notebook": 1},
            },
            "notebook_problems": [diagnostic],
            "global_usage": {},
            "chkstyle": {"status": chkstyle.get("status", 0) if isinstance(chkstyle, dict) else 0, "text": output[:max_output_chars] if truncated else output, "truncated": truncated, "chars": len(output), "omitted_chars": max(0, len(output) - (max_output_chars or len(output)))},
            "fixes": [],
            "text": text,
        }

# %% ../nbs/07_mcp.ipynb #mcpcat01
_MCP_DIAGNOSTIC_TOOL_CATALOG = {
    'healthcheck': {
        'feature': 'diagnostics',
        'usefulness': 'core',
        'tags': ('status', 'diagnostics', 'setup'),
        'description': 'Cheap liveness probe for the nbskill MCP server, installed version, capabilities, concurrency policy, and reconnect hints.',
        'when_to_use': 'Call first when checking that the MCP server is connected or after reinstalling/exporting tool signatures.',
        'combine_with': 'Could be folded into doctor, but a cheap health probe is useful enough to keep separate.',
    },
    'doctor': {
        'feature': 'diagnostics',
        'usefulness': 'core',
        'tags': ('status', 'diagnostics', 'error', 'warning', 'style'),
        'description': 'Scoped diagnostics for MCP setup, fatal notebook problems, warnings, private symbol leaks, and optional chkstyle output.',
        'when_to_use': "Use scopes='error', scopes='warning', scopes='style', or scopes='all' depending on the diagnostic depth needed.",
        'combine_with': 'Now absorbs private symbol warnings and scoped style diagnostics; healthcheck stays separate as a cheap probe.',
    },
}

# %% ../nbs/07_mcp.ipynb #mcpcat02
_MCP_READ_CONTEXT_TOOL_CATALOG = {
    'nb_overview': {
        'feature': 'read_context',
        'usefulness': 'core',
        'tags': ('read', 'notebook', 'orientation'),
        'description': 'Compact notebook map showing Markdown headings, imports, function/class/method signatures, and docstrings; ordinary Markdown docs are optional.',
        'when_to_use': 'Start here when opening a notebook or choosing which chapter or cell to inspect next.',
        'combine_with': 'Do not merge back into a broad reader; this intentionally stays small and scannable.',
    },
    'nb_chapter': {
        'feature': 'read_context',
        'usefulness': 'core',
        'tags': ('read', 'notebook', 'chapter'),
        'description': 'Notebook head plus one selected chapter found by chapter name, text query, or any cell id inside the chapter.',
        'when_to_use': 'Use after nb_overview when a section-level view is enough and line numbers are unnecessary.',
        'combine_with': 'Could share implementation with nb_cell, but the agent-facing context level is distinct.',
    },
    'nb_cell': {
        'feature': 'read_context',
        'usefulness': 'core',
        'tags': ('read', 'notebook', 'cell', 'line-numbers'),
        'description': 'Precise line-numbered cell view; query lookups include previous markdown, examples/tests, and caller/callee usage.',
        'when_to_use': 'Use before editing one cell, especially when line numbers, examples, or usage context matter.',
        'combine_with': 'Keep separate because it is the only reader that should expose line numbers and edit-local context.',
    },
}

# %% ../nbs/07_mcp.ipynb #mcpcat03
_MCP_READ_DOC_TOOL_CATALOG = {
    'show_doc': {
        'feature': 'read_context',
        'usefulness': 'situational',
        'tags': ('read', 'symbol', 'documentation'),
        'description': 'Symbol card showing location, nearest docs, signature/docstring, optional source/examples, and compact grouped usage.',
        'when_to_use': 'Use when the task starts from a public symbol and needs API-level context; use nb_cell for line-numbered edit context.',
        'combine_with': 'Could be covered by nb_cell plus symbol search, but it remains useful as a compact API documentation view.',
    },
}

# %% ../nbs/07_mcp.ipynb #mcpcat04
_MCP_CELL_EDIT_TOOL_CATALOG = {
    'edit_cell': {
        'feature': 'notebook_edit',
        'usefulness': 'core',
        'tags': ('edit', 'notebook', 'cell', 'source-lines'),
        'description': 'Replace one existing notebook cell from source_lines with validation, optional expected_hash, optional split_lines on empty lines, automatic export, and default-on feedback for exploratory/test cells.',
        'when_to_use': 'Use after nb_cell gives the id. Send source_lines directly; pass split_lines only for empty separator lines. Leave auto_feedback=True unless a speculative edit must not execute.',
        'combine_with': 'Use edit_cell_range for small line edits, insert_cells for new cells, and apply_notebook_edits for coordinated multi-step edits.',
    },
    'edit_cell_range': {
        'feature': 'notebook_edit',
        'usefulness': 'core',
        'tags': ('edit', 'notebook', 'cell', 'line-range'),
        'description': 'Replace a 1-based inclusive line range in one existing notebook cell from replacement_lines, with default-on feedback when the edited cell is exploratory or a test.',
        'when_to_use': 'Use for focused edits inside a large cell when preserving the rest of the cell matters.',
        'combine_with': 'Use edit_cell when replacing the entire cell.',
    },
    'insert_cells': {
        'feature': 'notebook_edit',
        'usefulness': 'core',
        'tags': ('edit', 'notebook', 'insert', 'source-lines'),
        'description': 'Insert one or more notebook cells before or after an anchor id from structured cell objects with source_lines, optional split_lines, and default-on feedback for exploratory/test cells.',
        'when_to_use': 'Use when adding notebook material. Each cell may include cell_type, source_lines, and split_lines.',
        'combine_with': 'Use apply_notebook_edits when inserts must be coordinated with replacements.',
    },
}

# %% ../nbs/07_mcp.ipynb #mcpcat05
_MCP_BATCH_EDIT_TOOL_CATALOG = {
    'apply_notebook_edits': {
        'feature': 'notebook_edit',
        'usefulness': 'core',
        'tags': ('edit', 'notebook', 'batch', 'source-lines'),
        'description': 'Apply structured notebook edit operations directly; operations use source_lines/replacement_lines and optional split_lines, never JSON plan text or plan files. Feedback runs by default only for exploratory/test cells.',
        'when_to_use': 'Use for coordinated edits across one or more notebooks when a single tool call is clearer than several direct edit calls.',
        'combine_with': 'This replaces the MCP-facing batch edit plan surface; CLI batch editing remains separate.',
    },
}

# %% ../nbs/07_mcp.ipynb #mcpcat06
_MCP_REVIEW_TOOL_CATALOG = {
    'exec_nb': {
        'feature': 'verification',
        'usefulness': 'core',
        'tags': ('execute', 'notebook', 'verify', 'safe'),
        'description': 'Execute a notebook, chapter, or cells up to an id with safe-mode controls and visible output/error capture; unsafe execution is routed through a CLI subprocess so signal-based timeouts run in a main interpreter without blocking MCP worker threads.',
        'when_to_use': 'Use after edits or before trusting notebook behavior; use check_only=True when outputs should not be written.',
        'combine_with': 'Keep separate because execution has distinct safety and concurrency semantics.',
    },
    'diff_nb': {
        'feature': 'review',
        'usefulness': 'core',
        'tags': ('review', 'notebook', 'diff'),
        'description': 'Notebook-aware code-cell diff that avoids raw .ipynb noise and can map generated Python diffs back to notebook owners.',
        'when_to_use': 'Use before final reporting or when reviewing notebook edits without expanding JSON metadata churn.',
        'combine_with': 'Could be grouped with style_check under review, but diff parameters and output are meaningfully different.',
    },
    'style_check': {
        'feature': 'review',
        'usefulness': 'core',
        'tags': ('review', 'style', 'hygiene', 'privacy'),
        'description': 'Notebook hygiene and style report including chkstyle output, private symbol warnings, duplicate imports, stored knowledge warnings, and order issues.',
        'when_to_use': 'Use after substantial edits or when a notebook feels structurally messy; stored behaviour steering regexes are included as warnings.',
        'combine_with': "Doctor can include style diagnostics with scopes='style'; standalone style_check remains the explicit review tool.",
    },
}

# %% ../nbs/07_mcp.ipynb #mcpcat07
_MCP_AGENT_TOOL_CATALOG = {
    'execute_plan': {
        'feature': 'agentic_planning',
        'usefulness': 'advanced',
        'tags': ('agent', 'edit', 'plan', 'notebook', 'project'),
        'description': 'Run a bounded edit-interactive plan against one notebook or a project-scoped set of notebooks.',
        'when_to_use': "Use scope='notebook' with notebook=... for one notebook, or scope='project' with notebooks=... for broad plans.",
        'combine_with': 'Combined former execute_project_plan into this tool via scope.',
    },
    'agent_workbench': {
        'feature': 'agentic_planning',
        'usefulness': 'advanced',
        'tags': ('agent', 'context', 'taste', 'contract', 'review'),
        'description': 'Prepare or execute a taste-aware small-diff workbench run with context, budgets, and gates.',
        'when_to_use': 'Use before autonomous implementation when taste, scope, context, and patch budgets need to be explicit.',
        'combine_with': 'Sits above execute_plan; execute_plan remains the bounded notebook executor.',
    },
    'symbol_graph': {
        'feature': 'symbol_analysis',
        'usefulness': 'situational',
        'tags': ('analysis', 'symbol', 'graph'),
        'description': "Analyze one symbol's definitions, callers, caller usage lines, and callees across notebooks.",
        'when_to_use': 'Use when understanding impact, dependencies, or call relationships around one symbol; request JSON/structured content for migration scripts.',
        'combine_with': "Private symbol reporting moved into doctor(scope='warning') and style_check output.",
    },
}

# %% ../nbs/07_mcp.ipynb #mcpcat08
_MCP_KNOWLEDGE_TOOL_CATALOG = {
    'store_knowledge': {
        'feature': 'knowledge',
        'usefulness': 'core',
        'tags': ('knowledge', 'memory', 'style', 'regex'),
        'description': 'Store or update one behaviour steering regex and note in the nbskill JSON memory file.',
        'when_to_use': 'Use after translating a remembered good or bad practice into a regex that should warn in future style checks.',
        'combine_with': 'add_behaviour_steering is a shorter regex-only helper; get_knowledge reads stored rules.',
    },
    'add_behaviour_steering': {
        'feature': 'knowledge',
        'usefulness': 'situational',
        'tags': ('knowledge', 'memory', 'regex'),
        'description': 'Add a behaviour steering regex with a generic note.',
        'when_to_use': 'Use when the regex itself is enough context, or prefer store_knowledge when a human-readable note matters.',
        'combine_with': 'store_knowledge is the richer form and style_check applies both kinds of stored rules.',
    },
    'get_knowledge': {
        'feature': 'knowledge',
        'usefulness': 'core',
        'tags': ('knowledge', 'memory', 'lookup'),
        'description': 'Return stored behaviour steering rules, optionally filtered by regex.',
        'when_to_use': 'Use before adding a similar rule, or when inspecting why style_check emitted a stored knowledge warning.',
        'combine_with': 'Use store_knowledge to add or update rules.',
    },
}

# %% ../nbs/07_mcp.ipynb #mcpcat09
_MCP_CONVERT_TOOL_CATALOG = {
    'py2nb': {
        'feature': 'conversion',
        'usefulness': 'situational',
        'tags': ('convert', 'python', 'notebook', 'folder'),
        'description': 'Convert one Python file or a folder of Python files into nbdev notebook source with pragmatic cell splitting.',
        'when_to_use': 'Use for file-level or folder-level Python-to-notebook migration.',
        'combine_with': 'Combined former py2nbs behavior into this file-or-folder converter.',
    },
    'py2nbdev': {
        'feature': 'conversion',
        'usefulness': 'situational',
        'tags': ('convert', 'project', 'nbdev'),
        'description': 'Create a pragmatic nbdev project from a pure-Python package or project tree.',
        'when_to_use': 'Use when bootstrapping a whole nbdev project rather than converting one module or folder.',
        'combine_with': 'Keep separate from py2nb because it creates project structure, not only notebooks.',
    },
    'new_nbdev_notebook': {
        'feature': 'conversion',
        'usefulness': 'situational',
        'tags': ('create', 'notebook', 'nbdev'),
        'description': 'Create a minimal nbdev source notebook and exported module.',
        'when_to_use': 'Use when adding a new nbdev notebook/module to a project.',
        'combine_with': 'Use py2nb when converting existing Python source instead of starting a blank notebook.',
    },
}

# %% ../nbs/07_mcp.ipynb #bb0721b9
_MCP_TOOL_CATALOG = {
    **_MCP_DIAGNOSTIC_TOOL_CATALOG,
    **_MCP_READ_CONTEXT_TOOL_CATALOG,
    **_MCP_READ_DOC_TOOL_CATALOG,
    **_MCP_CELL_EDIT_TOOL_CATALOG,
    **_MCP_BATCH_EDIT_TOOL_CATALOG,
    **_MCP_REVIEW_TOOL_CATALOG,
    **_MCP_AGENT_TOOL_CATALOG,
    **_MCP_KNOWLEDGE_TOOL_CATALOG,
    **_MCP_CONVERT_TOOL_CATALOG,
}

# %% ../nbs/07_mcp.ipynb #f7a620d9
def _mcp_tool_meta(name):
    "Return FastMCP registration metadata for one nbskill tool."
    info = _MCP_TOOL_CATALOG[name]
    return {
        "name": name,
        "description": info["description"],
        "tags": set(info["tags"]),
        "meta": {
            "feature": info["feature"],
            "usefulness": info["usefulness"],
            "when_to_use": info["when_to_use"],
            "combine_with": info["combine_with"],
        },
    }

# %% ../nbs/07_mcp.ipynb #mcppublic
_MCP_CAPABILITIES = ",".join(_MCP_TOOL_CATALOG)
mcp = FastMCP(
    "nbskill",
    instructions=(
        "Work notebook-first in nbdev projects. Feature areas are diagnostics, focused reads, "
        "notebook edits, verification/review, symbol analysis, agentic planning, and conversion. "
        "For reading, use nb_overview for a map, nb_chapter for one section, nb_cell for precise "
        "line-numbered edit context, and show_doc when starting from a public symbol. "
        "For edits, prefer edit_cell for one existing cell, edit_cell_range for partial cell edits, "
        "insert_cells for adding cells, and apply_notebook_edits for coordinated structured edits. Use split_lines only to split at empty source lines. "
        "Edit tools default to auto_feedback=True, which runs only exploratory or test cells in check-only mode and returns their output/errors. "
        "Use exec_nb, diff_nb, and style_check for verification and review; use doctor with "
        "scopes='error', 'warning', 'style', or 'all' for diagnostics. Chkstyle output only appears "
        "when doctor includes the style scope. Reserve execute_plan for agentic notebook/project edits "
        "Use store_knowledge/get_knowledge for behaviour steering memory; style_check applies stored regex rules as warnings. "
        "Normal tool output is concise; use detail='debug' only when troubleshooting. "
        "Notebook operations are concurrency-safe: calls touching the same notebook are serialized, "
        "calls touching different notebooks can run in parallel, and execution uses a global semaphore. "
        "Keep documentation before exported code and show-off examples after it."
    ),
)

# %% ../nbs/07_mcp.ipynb #mcphealthch
@mcp.tool(**_mcp_tool_meta("healthcheck"))
def _healthcheck_tool(detail: str = "summary") -> ToolResult:
    "Return lightweight nbskill MCP status and point deeper diagnostics to doctor."
    data = _status_data()
    full_output = "\n".join([
        "nbskill mcp ok",
        f"version={data['version']}",
        f"cwd={Path.cwd()}",
        f"python={sys.executable}",
        f"pid={os.getpid()}",
        f"capabilities={_MCP_CAPABILITIES}",
        "parallel=same-notebook operations serialized; different notebooks may run in parallel",
        "execution=global semaphore with one active safe notebook execution",
        "diagnostics=run doctor(scopes='error,warning') for fatal problems and warnings; add style for chkstyle",
        "schema_refresh=restart or reconnect the MCP client after reinstall/export to refresh tool schemas",
    ])
    return mcp_tool_result("healthcheck", {"detail": detail}, full_output, detail=detail, status=data, capabilities=_MCP_CAPABILITIES.split(","))

# %% ../nbs/07_mcp.ipynb #mcptool01
@mcp.tool(**_mcp_tool_meta("doctor"))
def doctor_tool(
    path: str = ".", scopes: str = "error,warning", detail: str = "summary",
    fix: bool = False, reset: bool = False, skip_folder_re: str | None = None,
    skip_path: str | None = None, max_output_chars: int = 12000,
    max_diagnostics: int = 200,
) -> ToolResult:
    "Report scoped MCP diagnostics: errors, warnings, and optional chkstyle/style details."
    arguments = dict(path=path, scopes=scopes, detail=detail, fix=fix, reset=reset, skip_folder_re=skip_folder_re, skip_path=skip_path, max_output_chars=max_output_chars, max_diagnostics=max_diagnostics)
    report = _doctor_report(path=path, detail=detail, fix=fix, reset=reset, capabilities=_MCP_CAPABILITIES, scopes=scopes, skip_folder_re=skip_folder_re, skip_path=skip_path, max_output_chars=max_output_chars, max_diagnostics=max_diagnostics)
    return mcp_tool_result(
        "doctor", arguments, report["text"], detail=detail,
        warnings=report["issues"], hints=report["hints"], doctor=report,
    )

# %% ../nbs/07_mcp.ipynb #mcpnboverv
@mcp.tool(**_mcp_tool_meta("nb_overview"))
def _nb_overview_tool(nb_path: str, include_docs: bool = False, detail: str = "summary") -> ToolResult:
    "Show headings, imports, signatures, and docstrings, optionally with non-heading Markdown docs."
    arguments = dict(nb_path=nb_path, include_docs=include_docs, detail=detail)
    full_output = capture_notebook_call(nb_overview, nb_path, nb_path=nb_path, include_docs=include_docs, verbose=True)
    return mcp_tool_result("nb_overview", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcpnbchapt
@mcp.tool(**_mcp_tool_meta("nb_chapter"))
def _nb_chapter_tool(nb_path: str, query: str | None = None, name: str | None = None, any_cell_id: str | None = None, detail: str = "summary") -> ToolResult:
    "Show the notebook head plus one selected chapter."
    arguments = dict(nb_path=nb_path, query=query, name=name, any_cell_id=any_cell_id, detail=detail)
    full_output = capture_notebook_call(nb_chapter, nb_path, nb_path=nb_path, query=query, name=name, any_cell_id=any_cell_id)
    return mcp_tool_result("nb_chapter", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcpnbcell
@mcp.tool(**_mcp_tool_meta("nb_cell"))
def _nb_cell_tool(nb_path: str, query: str | None = None, id: str | None = None, detail: str = "summary") -> ToolResult:
    "Show one selected cell; query lookups include previous docs, examples/tests, and caller/callee usage."
    arguments = dict(nb_path=nb_path, query=query, id=id, detail=detail)
    full_output = capture_notebook_call(nb_cell, nb_path, nb_path=nb_path, query=query, id=id)
    return mcp_tool_result("nb_cell", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcpshowdoc
@mcp.tool(**_mcp_tool_meta("show_doc"))
def _show_doc_tool(path: str, symbol: str, context: int = 2, source: bool = False, show_ids: bool = False, detail: str = "summary") -> ToolResult:
    "Show a compact symbol card with location, docs, definition, optional source/examples, and grouped usage."
    arguments = dict(path=path, symbol=symbol, context=context, source=source, show_ids=show_ids, detail=detail)
    full_output = capture_notebook_call(show_doc, path, path=path, symbol=symbol, context=context, source=source, show_ids=show_ids)
    return mcp_tool_result("show_doc", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcptool06
@mcp.tool(**_mcp_tool_meta("edit_cell"))
def edit_cell_tool(
    path: str, cell_id: str, source_lines: list[str], cell_type: str = "code",
    split_lines: list[int] | None = None, validate_code: bool = True,
    expected_hash: str | None = None, auto_feedback: bool = True,
    feedback_timeout: int = 10, feedback_safe: bool = True, detail: str = "summary",
) -> ToolResult:
    "Replace one existing notebook cell from source_lines."
    arguments = dict(path=path, cell_id=cell_id, source_lines=source_lines, cell_type=cell_type, split_lines=split_lines, validate_code=validate_code, expected_hash=expected_hash, auto_feedback=auto_feedback, feedback_timeout=feedback_timeout, feedback_safe=feedback_safe, detail=detail)
    if warning := _mcp_expected_hash_warning(path, cell_id, expected_hash):
        return mcp_tool_result("edit_cell", arguments, warning["message"], detail=detail, warnings=[warning], ok=False)
    start = _mcp_cell_index(path, cell_id)
    cell_count = _mcp_structured_cell_count([dict(source_lines=source_lines, cell_type=cell_type, split_lines=split_lines)], cell_type)
    full_output = replace_notebook_cell(path, cell_id, source_lines, cell_type=cell_type, split_lines=split_lines, validate_code=validate_code, auto_feedback=False)
    cell_ids = _mcp_cell_ids_from_index(path, start, cell_count)
    full_output = _append_mcp_feedback(full_output, path, cell_ids, auto_feedback, feedback_timeout, feedback_safe)
    return mcp_tool_result("edit_cell", arguments, full_output, detail=detail, ok=True, after_hash=_mcp_cell_source_hash(path, cell_id))

# %% ../nbs/07_mcp.ipynb #mcptool07
@mcp.tool(**_mcp_tool_meta("edit_cell_range"))
def edit_cell_range_tool(
    path: str, cell_id: str, start_line: int, end_line: int,
    replacement_lines: list[str], validate_code: bool = True,
    expected_hash: str | None = None, auto_feedback: bool = True,
    feedback_timeout: int = 10, feedback_safe: bool = True, detail: str = "summary",
) -> ToolResult:
    "Replace a 1-based inclusive line range in one existing notebook cell."
    arguments = dict(path=path, cell_id=cell_id, start_line=start_line, end_line=end_line, replacement_lines=replacement_lines, validate_code=validate_code, expected_hash=expected_hash, auto_feedback=auto_feedback, feedback_timeout=feedback_timeout, feedback_safe=feedback_safe, detail=detail)
    if warning := _mcp_expected_hash_warning(path, cell_id, expected_hash):
        return mcp_tool_result("edit_cell_range", arguments, warning["message"], detail=detail, warnings=[warning], ok=False)
    full_output = replace_notebook_range(path, cell_id, start_line, end_line, replacement_lines, validate_code=validate_code, auto_feedback=False)
    full_output = _append_mcp_feedback(full_output, path, [cell_id], auto_feedback, feedback_timeout, feedback_safe)
    return mcp_tool_result("edit_cell_range", arguments, full_output, detail=detail, ok=True, after_hash=_mcp_cell_source_hash(path, cell_id))

# %% ../nbs/07_mcp.ipynb #mcptool08
@mcp.tool(**_mcp_tool_meta("insert_cells"))
def insert_cells_tool(
    path: str, anchor_id: str, where: str = "after", cells: list[dict] | None = None,
    split_lines: list[int] | None = None, validate_code: bool = True,
    default_cell_type: str = "code", auto_feedback: bool = True,
    feedback_timeout: int = 10, feedback_safe: bool = True, detail: str = "summary",
) -> ToolResult:
    "Insert structured notebook cells before or after an anchor id."
    if where not in {"before", "after"}: raise ValueError("where must be 'before' or 'after'")
    if split_lines is not None:
        if len(cells or []) != 1: raise ValueError("top-level split_lines requires exactly one cell")
        cells = [dict(cells[0], split_lines=split_lines)]
    arguments = dict(path=path, anchor_id=anchor_id, where=where, cells=cells, split_lines=split_lines, validate_code=validate_code, default_cell_type=default_cell_type, auto_feedback=auto_feedback, feedback_timeout=feedback_timeout, feedback_safe=feedback_safe, detail=detail)
    anchor_index = _mcp_cell_index(path, anchor_id)
    start = anchor_index if where == "before" else anchor_index + 1
    cell_count = _mcp_structured_cell_count(cells, default_cell_type)
    full_output = insert_notebook_cells(path, anchor_id, where, cells, validate_code=validate_code, default_cell_type=default_cell_type, auto_feedback=False)
    cell_ids = _mcp_cell_ids_from_index(path, start, cell_count)
    full_output = _append_mcp_feedback(full_output, path, cell_ids, auto_feedback, feedback_timeout, feedback_safe)
    return mcp_tool_result("insert_cells", arguments, full_output, detail=detail, ok=True)

# %% ../nbs/07_mcp.ipynb #mcptool09
@mcp.tool(**_mcp_tool_meta("apply_notebook_edits"))
def apply_notebook_edits_tool(
    path: str, edits: list[dict], validate_code: bool = True,
    default_cell_type: str = "code", auto_feedback: bool = True,
    feedback_timeout: int = 10, feedback_safe: bool = True, detail: str = "summary",
) -> ToolResult:
    "Apply structured notebook edit operations without JSON plan text."
    if not edits: raise ValueError("Pass at least one edit")
    arguments = dict(path=path, edits=edits, validate_code=validate_code, default_cell_type=default_cell_type, auto_feedback=auto_feedback, feedback_timeout=feedback_timeout, feedback_safe=feedback_safe, detail=detail)
    warnings = [
        warning for edit in edits
        if (warning := _mcp_expected_hash_warning(str(edit.get("path") or path), edit.get("cell_id"), edit.get("expected_hash")))
    ]
    if warnings:
        return mcp_tool_result("apply_notebook_edits", arguments, "Skipped apply_notebook_edits because one or more expected_hash checks failed.", detail=detail, warnings=warnings, ok=False)
    chunks = []
    for index, edit in enumerate(edits, 1):
        edit_path, start, cell_count = _mcp_feedback_location(path, edit, default_cell_type)
        output = apply_notebook_edit(edit, path, validate_code=validate_code, default_cell_type=default_cell_type, auto_feedback=False)
        cell_ids = _mcp_cell_ids_from_index(edit_path, start, cell_count)
        output = _append_mcp_feedback(output, edit_path, cell_ids, auto_feedback, feedback_timeout, feedback_safe)
        chunks.append(f"#{index} {edit.get('op')}\n{output}".rstrip())
    return mcp_tool_result("apply_notebook_edits", arguments, "\n\n".join(chunks), detail=detail, ok=True)
    return mcp_tool_result("apply_notebook_edits", arguments, "\n\n".join(chunks), detail=detail, ok=True)

# %% ../nbs/07_mcp.ipynb #mcptool10
@mcp.tool(**_mcp_tool_meta("exec_nb"))
def exec_nb_tool(
    path: str, dest: str | None = None, exc_stop: bool = False, up2id: int | str | None = None,
    chapter: str | None = None, timeout: int = 30, show_output: bool = True,
    verbose: bool = False, safe: bool = True, allow: str | None = None,
    ok_dests: str | None = None, cache_httpx: bool = False, cache_dir: str | None = None,
    cache_domains: str | None = None, allow_new: bool = False, check_only: bool = False,
    detail: str = "summary",
) -> ToolResult:
    "Execute a notebook and return visible outputs/errors. Use check_only=True to avoid writing outputs."
    arguments = dict(path=path, dest=dest, exc_stop=exc_stop, up2id=up2id, chapter=chapter, timeout=timeout, show_output=show_output, verbose=verbose, safe=safe, allow=allow, ok_dests=ok_dests, cache_httpx=cache_httpx, cache_dir=cache_dir, cache_domains=cache_domains, allow_new=allow_new, check_only=check_only, detail=detail)
    if safe:
        full_output = capture_notebook_call(exec_nb, path, dest or path, **{k: v for k, v in arguments.items() if k != "detail"})
    else:
        full_output = _capture_exec_nb_cli_call(arguments)
    warnings = []
    if safe and "PermissionError: Audit:" in full_output:
        warnings.append(_warning(
            "safe-exec-audit-block",
            "Safe execution blocked an audited operation.",
            "For trusted notebooks, rerun with safe=False.",
        ))
    return mcp_tool_result("exec_nb", arguments, full_output, detail=detail, warnings=warnings)

# %% ../nbs/07_mcp.ipynb #mcpdiffnb
@mcp.tool(**_mcp_tool_meta("diff_nb"))
def _diff_nb_tool(path: str, ref_a: str | None = "HEAD", ref_b: str | None = None, adds: bool = True, changes: bool = True, dels: bool = False, cell_id: str | None = None, after_id: str | None = None, show_owner: bool = False, detail: str = "summary") -> ToolResult:
    "Diff notebook code cells without expanding raw notebook JSON; optionally filter by cell id or map generated Python to its owner."
    arguments = dict(path=path, ref_a=ref_a, ref_b=ref_b, adds=adds, changes=changes, dels=dels, cell_id=cell_id, after_id=after_id, show_owner=show_owner, detail=detail)
    if show_owner and Path(path).suffix == ".py":
        return mcp_tool_result("diff_nb", arguments, _owner_output(path), detail=detail)
    full_output = capture_notebook_call(diff_nb, path, **{k: v for k, v in arguments.items() if k not in {"show_owner", "detail"}})
    return mcp_tool_result("diff_nb", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcptool12
@mcp.tool(**_mcp_tool_meta("execute_plan"))
def execute_plan_tool(
    plan: str, notebook: str | None = None, scope: str = "notebook",
    notebooks: str | None = None, model: str | None = None, max_steps: int = 20,
    timeout: int = 30,
    detail: str = "summary",
) -> ToolResult:
    "Run a bounded edit-interactive loop against one notebook or a project notebook set."
    arguments = dict(plan=plan, notebook=notebook, scope=scope, notebooks=notebooks, model=model, max_steps=max_steps, timeout=timeout, detail=detail)
    mode = "project" if scope == "project" or notebooks else "notebook"
    if mode == "project":
        project_args = dict(plan=plan, notebooks=notebooks, model=model, max_steps=max_steps, timeout=timeout, dry_run=False)
        full_output = capture_call(execute_project_plan, **project_args)
        return mcp_tool_result("execute_plan", arguments, full_output, detail=detail)
    if not notebook: raise ValueError("notebook is required when scope='notebook'")
    notebook_args = dict(notebook=notebook, plan=plan, model=model, max_steps=max_steps, timeout=timeout, dry_run=False)
    result = execute_plan(**notebook_args)
    full_output = plan_result_text(result)
    tool_result = mcp_tool_result("execute_plan", arguments, full_output, detail=detail)
    if isinstance(result, dict):
        tool_result.structured_content["history"] = result.get("history", [])
        tool_result.structured_content["summary"] = result.get("summary", "")
        tool_result.structured_content["execute_plan"] = result
    return tool_result

# %% ../nbs/07_mcp.ipynb #mcptool13
@mcp.tool(**_mcp_tool_meta("agent_workbench"))
def agent_workbench_tool(
    goal: str, notebook: str | None = None, contract_file: str | None = None,
    execute: bool = False, max_steps: int = 8, timeout: int = 30,
    detail: str = "summary",
) -> ToolResult:
    "Prepare or execute a taste-aware small-diff workbench run."
    arguments = dict(goal=goal, notebook=notebook, contract_file=contract_file, execute=execute, max_steps=max_steps, timeout=timeout, detail=detail)
    result = agent_workbench_result(
        goal, notebook=notebook, contract_file=contract_file, execute=execute,
        max_steps=max_steps, timeout=timeout,
    )
    full_output = result.get("rendered_plan") or result.get("summary", "")
    tool_result = mcp_tool_result("agent_workbench", arguments, full_output, detail=detail)
    if isinstance(result, dict): tool_result.structured_content["agent_workbench"] = result
    return tool_result

# %% ../nbs/07_mcp.ipynb #mcpsymbolg
@mcp.tool(**_mcp_tool_meta("symbol_graph"))
def _symbol_graph_tool(path: str = "nbs", symbol: str = "", json_output: bool = False, detail: str = "summary") -> ToolResult:
    "Show definitions, callers, and callees for one notebook symbol."
    arguments = dict(path=path, symbol=symbol, json_output=json_output, detail=detail)
    full_output = capture_call(symbol_graph, path=path, symbol=symbol, json_output=json_output)
    result = mcp_tool_result("symbol_graph", arguments, full_output, detail=detail)
    if symbol:
        result.structured_content["symbol_graph"] = symbol_graph_public_data(symbol_graph_data(path, symbol))
    return result

# %% ../nbs/07_mcp.ipynb #mcptool15
@mcp.tool(**_mcp_tool_meta("style_check"))
def style_check_tool(
    path: str = ".", skip_folder_re: str | None = None, skip_path: str | None = None,
    strict: bool = False, delete_after_output: bool = False,
    max_output_chars: int = 12000, max_diagnostics: int = 200, fix: bool = False,
    changed_only: bool = False, ref_a: str | None = "HEAD", ref_b: str | None = None,
    detail: str = "summary",
) -> ToolResult:
    "Print capped chkstyle output, notebook hygiene warnings, private symbol warnings, and global tool usage."
    arguments = dict(path=path, skip_folder_re=skip_folder_re, skip_path=skip_path, strict=strict, delete_after_output=delete_after_output, max_output_chars=max_output_chars, max_diagnostics=max_diagnostics, fix=fix, changed_only=changed_only, ref_a=ref_a, ref_b=ref_b, detail=detail)
    style_output = capture_call(style_check, **{k: v for k, v in arguments.items() if k != "detail"})
    private_output = _private_symbol_report_text(path)
    full_output = "\n\n".join(chunk for chunk in [private_output, style_output] if chunk)
    report = style_report(
        path, max_output_chars=max_output_chars, max_diagnostics=max_diagnostics,
        changed_only=changed_only, ref_a=ref_a, ref_b=ref_b,
        skip_folder_re=skip_folder_re, skip_path=skip_path,
    )
    report["private_symbol_report"] = private_output
    return mcp_tool_result("style_check", arguments, full_output, max_output_chars=max_output_chars, detail=detail, style_report=report)

# %% ../nbs/07_mcp.ipynb #mcpstorekn
@mcp.tool(**_mcp_tool_meta("store_knowledge"))
def _store_knowledge_tool(apply_regex: str, note: str, path: str | None = None, detail: str = "summary") -> ToolResult:
    "Store or update one behaviour steering regex and note."
    arguments = dict(apply_regex=apply_regex, note=note, path=path, detail=detail)
    full_output = capture_call(store_knowledge, apply_regex=apply_regex, note=note, path=path)
    return mcp_tool_result("store_knowledge", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcpaddbeha
@mcp.tool(**_mcp_tool_meta("add_behaviour_steering"))
def _add_behaviour_steering_tool(regex: str, path: str | None = None, detail: str = "summary") -> ToolResult:
    "Add a behaviour steering regex with a generic note."
    arguments = dict(regex=regex, path=path, detail=detail)
    full_output = capture_call(add_behaviour_steering, regex=regex, path=path)
    return mcp_tool_result("add_behaviour_steering", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcpgetknow
@mcp.tool(**_mcp_tool_meta("get_knowledge"))
def _get_knowledge_tool(regex: str | None = None, path: str | None = None, detail: str = "summary") -> ToolResult:
    "Return stored behaviour steering rules, optionally filtered by regex."
    arguments = dict(regex=regex, path=path, detail=detail)
    full_output = capture_call(get_knowledge, regex=regex, path=path)
    return mcp_tool_result("get_knowledge", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcptool19
@mcp.tool(**_mcp_tool_meta("py2nb"))
def py2nb_tool(
    path: str, nbs_path: str = "nbs", dest: str | None = None, recursive: bool = True,
    maxdepth: int | None = None, preserve_tree: bool = True, class_lines: int = 100,
    method_lines: int = 10, package: str | None = None, include: str | None = None,
    exclude: str | None = None, skip_init: bool = True, include_tests: bool = False,
    force: bool = True, detail: str = "summary",
) -> ToolResult:
    "Convert one Python file or a folder of Python files into nbdev notebook source."
    arguments = dict(path=path, nbs_path=nbs_path, dest=dest, recursive=recursive, maxdepth=maxdepth, preserve_tree=preserve_tree, class_lines=class_lines, method_lines=method_lines, package=package, include=include, exclude=exclude, skip_init=skip_init, include_tests=include_tests, force=force, detail=detail)
    full_output = capture_call(py2nb, **{k: v for k, v in arguments.items() if k != "detail"}, dry_run=False)
    return mcp_tool_result("py2nb", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcppy2nbdev
@mcp.tool(**_mcp_tool_meta("py2nbdev"))
def _py2nbdev_tool(source: str, dest: str, package: str | None = None, nbs_path: str = "nbs", force: bool = False, run_validation: bool = True, detail: str = "summary") -> ToolResult:
    "Create a pragmatic nbdev project from a pure-Python package."
    arguments = dict(source=source, dest=dest, package=package, nbs_path=nbs_path, force=force, run_validation=run_validation, detail=detail)
    full_output = capture_call(py2nbdev, **{k: v for k, v in arguments.items() if k != "detail"}, dry_run=False)
    return mcp_tool_result("py2nbdev", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #mcptool21
@mcp.tool(**_mcp_tool_meta("new_nbdev_notebook"))
def new_nbdev_notebook_tool(
    name: str, default_exp: str | None = None, title: str | None = None,
    nbs_path: str = "nbs", force: bool = False, detail: str = "summary",
) -> ToolResult:
    "Create a minimal nbdev source notebook and exported module."
    arguments = dict(name=name, default_exp=default_exp, title=title, nbs_path=nbs_path, force=force, detail=detail)
    full_output = capture_call(new_nbdev_notebook, **{k: v for k, v in arguments.items() if k != "detail"}, dry_run=False)
    return mcp_tool_result("new_nbdev_notebook", arguments, full_output, detail=detail)

# %% ../nbs/07_mcp.ipynb #6daab47d
def create_mcp():
    "Return the public nbskill FastMCP server."
    return mcp

# %% ../nbs/07_mcp.ipynb #bc41ce66
def main(
    transport: str = "stdio",  # MCP transport; stdio is what Codex/Claude use for local servers
    show_banner: bool = False,  # Show FastMCP startup banner
):
    "Run the nbskill MCP server."
    mcp.run(transport=transport, show_banner=show_banner)
