# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_skill.ipynb.

# %% auto #0
__all__ = ['install_nbskill', 'install_nbskill_cli']

# %% ../nbs/06_skill.ipynb #a23594cd
import json, subprocess, tomllib
from importlib.resources import files
from pathlib import Path

from .foundation import install_nbdev_pre_commit_hooks

# %% ../nbs/06_skill.ipynb #aaccbabb
def _write_if_changed(path, text):
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    if old == text: return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True

# %% ../nbs/06_skill.ipynb #45e4c0e8
def _install_skill_tree(root, skill_name, skill_text, references, overwrite=True):
    """Copy changed skill files and leave byte-identical files untouched."""
    dst_dir = root / skill_name
    files_to_install = [(dst_dir / "SKILL.md", skill_text)]
    if references.is_dir():
        files_to_install += [
            (dst_dir / "references" / ref.name, ref.read_text(encoding="utf-8"))
            for ref in references.iterdir() if ref.is_file()
        ]
    changed, unchanged = [], []
    for path,text in files_to_install:
        if path.exists() and path.read_text(encoding="utf-8") != text and not overwrite:
            raise FileExistsError(path)
        if _write_if_changed(path, text): changed.append(path)
        else: unchanged.append(path)
    return changed, unchanged

# %% ../nbs/06_skill.ipynb #6a186b66
def _skill_roots(target, skills_dir):
    target = target.lower()
    if target == "cursor": return target, []
    if skills_dir: return target, [Path(skills_dir).expanduser()]
    if target == "codex": return target, [Path.home() / ".codex" / "skills"]
    if target in {"claude", "claude-code", "claude_code"}: return target, [Path.home() / ".claude" / "skills"]
    if target == "both": return target, [Path.home() / ".codex" / "skills", Path.home() / ".claude" / "skills"]
    raise ValueError("target must be codex, claude, cursor, both, or use skills_dir")

# %% ../nbs/06_skill.ipynb #8828875e
def _install_skill_files(roots, skill_name, overwrite):
    package = files("nbskill")
    skill_text = package.joinpath("SKILL.md").read_text(encoding="utf-8")
    references = package.joinpath("references")
    installed, unchanged = [], []
    for root in roots:
        changed, current = _install_skill_tree(root, skill_name, skill_text, references, overwrite)
        installed += changed
        unchanged += current
    return installed, unchanged

# %% ../nbs/06_skill.ipynb #dab79c19
def install_nbskill(
    target: str = "codex",  # codex, claude, cursor, both, or custom when skills_dir is set
    skills_dir: str | None = None,  # Parent skills directory; skill is installed below jupyter-notebooks
    skill_name: str = "jupyter-notebooks",  # Skill folder name
    overwrite: bool = True,  # Update stale managed files
    install_hooks: bool = False,  # Install nbdev-clean/nbdev-test pre-commit hooks in the current repo
    reference_roots: str = "~/projects",  # Local Git repositories to add to the reference index
    index_references: bool = True,  # Index references during installation
):
    """Install current Python workflow instructions."""
    target, roots = _skill_roots(target, skills_dir)
    installed, unchanged = _install_skill_files(roots, skill_name, overwrite)
    hooks = install_nbdev_pre_commit_hooks(Path.cwd()) if install_hooks else {"installed": False, "reason": "disabled"}
    from nbskill.knowledge import reference_discover
    reference_index = reference_discover(roots=reference_roots, ingest=index_references)
    for path in installed: print(f"Installed {path}")
    if hooks.get("installed"): print(f"Installed nbdev pre-commit hook at {hooks['hook']}")
    return {"installed": installed, "unchanged": unchanged, "hooks": hooks, "references": reference_index}

# %% ../nbs/06_skill.ipynb #f50fbb2c
def install_nbskill_cli():
    "Install notebook workflow instructions from the command line."
    import argparse
    parser = argparse.ArgumentParser(description="Install nbskill Python workflow instructions.")
    parser.add_argument("--target", default="codex")
    parser.add_argument("--skills-dir")
    parser.add_argument("--skill-name", default="jupyter-notebooks")
    parser.add_argument("--no-overwrite", dest="overwrite", action="store_false")
    parser.add_argument("--install-hooks", action="store_true")
    parser.add_argument("--reference-roots", default="~/projects")
    parser.add_argument("--no-index-references", dest="index_references", action="store_false")
    install_nbskill(**vars(parser.parse_args()))
