"""Serialize writes to the same notebook while allowing unrelated notebooks to proceed.

Concurrent edits can otherwise read the same old file and overwrite one another. `notebook_locks` holds a re-entrant Python lock and an OS file lock from read through commit. Paths are normalized and acquired in a stable order, so overlapping notebook transactions wait while independent notebooks can proceed. `execution_slot` serializes execution within one Python process, where kernels and output capture share state.

```python
from nbskill.parallel import notebook_key, notebook_locks, execution_slot
from nbskill.foundation import write_demo_notebook
from pathlib import Path
```

### `notebook_key`

`notebook_key` resolves relative paths and `..` before choosing a lock. Two spellings of the same notebook must use the same lock even before the notebook exists:

```python
relative_key = notebook_key("nbs/../nbs/01_read.ipynb")
assert relative_key == notebook_key("nbs/01_read.ipynb")
Path(relative_key).name
```

### `notebook_locks`

`notebook_locks` acquires any number of notebook paths in sorted order and releases them on exit. The locks are re-entrant so a transaction can call another notebook helper without deadlocking its own thread. Acquire locks before reading the file and retain them until the write finishes:

```python
with write_demo_notebook("09_parallel_usage.ipynb") as path:
    with notebook_locks(path):
        with notebook_locks(path): lock_status = "nested notebook transaction completed"
lock_status
```

### `execution_slot`

`execution_slot` protects execution state shared by calls in one Python process. The gate is re-entrant, allowing an execution wrapper to call a lower-level executor. Per-notebook OS locks protect file transactions across processes:

```python
with execution_slot():
    with execution_slot(): execution_status = "nested execution call completed"
execution_status
```

Docs: https://MorsCerta-crypto.github.io/nbskill/parallel.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_parallel.ipynb.

# %% auto #0
__all__ = ['notebook_key', 'notebook_locks', 'execution_slot']

# %% ../nbs/09_parallel.ipynb #dbb7eddf
import fcntl, hashlib, threading, tempfile
from contextlib import contextmanager
from pathlib import Path

# %% ../nbs/09_parallel.ipynb #9eb56702
_LOCKS_GUARD = threading.Lock()
_NOTEBOOK_LOCKS = {}
_PROCESS_LOCKS_GUARD = threading.Lock()
_PROCESS_LOCKS = {}
_PROCESS_LOCK_ROOT = Path(tempfile.gettempdir()) / "nbskill-notebook-locks"
_EXECUTION_SEMAPHORE = threading.RLock()

# %% ../nbs/09_parallel.ipynb #be270912
def notebook_key(path):
    "Return a stable lock key for a notebook path."
    if path is None: return None
    return str(Path(path).expanduser().resolve(strict=False))

# %% ../nbs/09_parallel.ipynb #476fd308
def _notebook_lock(key):
    with _LOCKS_GUARD:
        lock = _NOTEBOOK_LOCKS.get(key)
        if lock is None:
            lock = threading.RLock()
            _NOTEBOOK_LOCKS[key] = lock
        return lock

# %% ../nbs/09_parallel.ipynb #0c02e64f
def _process_lock_path(key):
    digest = hashlib.sha256(key.encode()).hexdigest()
    return _PROCESS_LOCK_ROOT / f"{digest}.lock"

# %% ../nbs/09_parallel.ipynb #440d012d
def _acquire_process_lock(key):
    with _PROCESS_LOCKS_GUARD:
        current = _PROCESS_LOCKS.get(key)
        if current:
            _PROCESS_LOCKS[key] = (current[0], current[1] + 1)
            return
        _PROCESS_LOCK_ROOT.mkdir(parents=True, exist_ok=True)
        handle = _process_lock_path(key).open("a+")
        _PROCESS_LOCKS[key] = (handle, 1)
    try: fcntl.flock(handle, fcntl.LOCK_EX)
    except BaseException:
        with _PROCESS_LOCKS_GUARD: del _PROCESS_LOCKS[key]
        handle.close()
        raise

# %% ../nbs/09_parallel.ipynb #ac9c1d37
def _release_process_lock(key):
    with _PROCESS_LOCKS_GUARD:
        handle, depth = _PROCESS_LOCKS[key]
        if depth > 1:
            _PROCESS_LOCKS[key] = (handle, depth - 1)
            return
        del _PROCESS_LOCKS[key]
    fcntl.flock(handle, fcntl.LOCK_UN)
    handle.close()

# %% ../nbs/09_parallel.ipynb #59d16a3a
@contextmanager
def notebook_locks(*paths):
    "Acquire per-notebook locks in a stable order."
    keys = sorted({notebook_key(path) for path in paths if notebook_key(path) is not None})
    locks = [_notebook_lock(key) for key in keys]
    acquired, acquired_locks = [], []
    try:
        for lock in locks:
            lock.acquire()
            acquired_locks.append(lock)
        for key in keys:
            _acquire_process_lock(key)
            acquired.append(key)
        yield
    finally:
        for key in reversed(acquired): _release_process_lock(key)
        for lock in reversed(acquired_locks): lock.release()

# %% ../nbs/09_parallel.ipynb #01f6a5cf
@contextmanager
def execution_slot():
    "Serialize notebook execution across parallel Python calls."
    _EXECUTION_SEMAPHORE.acquire()
    try:
        yield
    finally:
        _EXECUTION_SEMAPHORE.release()
