# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_parallel.ipynb.

# %% auto #0
__all__ = ['notebook_key', 'notebook_locks', 'execution_slot']

# %% ../nbs/09_parallel.ipynb #dbb7eddf
import threading
from contextlib import contextmanager
from pathlib import Path

# %% ../nbs/09_parallel.ipynb #9eb56702
_LOCKS_GUARD = threading.Lock()
_NOTEBOOK_LOCKS = {}
_EXECUTION_SEMAPHORE = threading.Semaphore(1)

# %% ../nbs/09_parallel.ipynb #be270912
def notebook_key(path):
    "Return a stable lock key for a notebook path."
    if path is None: return None
    return str(Path(path).expanduser().resolve(strict=False))

# %% ../nbs/09_parallel.ipynb #476fd308
def _notebook_lock(key):
    with _LOCKS_GUARD:
        lock = _NOTEBOOK_LOCKS.get(key)
        if lock is None:
            lock = threading.RLock()
            _NOTEBOOK_LOCKS[key] = lock
        return lock

# %% ../nbs/09_parallel.ipynb #59d16a3a
@contextmanager
def notebook_locks(*paths):
    "Acquire per-notebook locks in a stable order."
    keys = sorted({notebook_key(path) for path in paths if notebook_key(path) is not None})
    locks = [_notebook_lock(key) for key in keys]
    for lock in locks: lock.acquire()
    try:
        yield
    finally:
        for lock in reversed(locks): lock.release()

# %% ../nbs/09_parallel.ipynb #01f6a5cf
@contextmanager
def execution_slot():
    "Serialize notebook execution across parallel MCP calls."
    _EXECUTION_SEMAPHORE.acquire()
    try:
        yield
    finally:
        _EXECUTION_SEMAPHORE.release()
