# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/data/readme-demo/sample_tool.ipynb.

# %% auto #0
__all__ = ['double']

# %% ../nbs/data/readme-demo/sample_tool.ipynb #00845420
def double(x):
    return x * 2
