# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_skill.ipynb.

# %% auto #0
__all__ = ['build_skill_from_readme', 'install_nbskill']

# %% ../nbs/06_skill.ipynb #a23594cd
from importlib.resources import files
from pathlib import Path

from fastcore.script import call_parse

from .foundation import cli_return, tracked_call

# %% ../nbs/06_skill.ipynb #skillbld
_SKILL_START = "<!-- nbskill-skill:start -->"
_SKILL_END = "<!-- nbskill-skill:end -->"
_SKILL_FRONTMATTER = """---
name: jupyter-notebooks
description: Work notebook-first in nbdev projects with nbskill MCP tools for reading, writing, updating, and executing notebooks without raw JSON.
---"""


def _marked_readme_section(text, start=_SKILL_START, end=_SKILL_END):
    try:
        body = text.split(start, 1)[1].split(end, 1)[0]
    except IndexError as exc:
        raise ValueError(f"README is missing {start!r} and {end!r} markers") from exc
    return body.strip()


def _skill_frontmatter(out_path):
    path = Path(out_path)
    if path.exists():
        text = path.read_text(encoding="utf-8")
        if text.startswith("---\n"):
            parts = text.split("\n---", 1)
            if len(parts) == 2: return f"---{parts[0][3:]}\n---"
    return _SKILL_FRONTMATTER


@call_parse
@tracked_call
def build_skill_from_readme(
    readme_path: str = "README.md",  # README containing the marked skill section
    out_path: str = "nbskill/SKILL.md",  # Skill file to write
):
    "Build SKILL.md from the marked section of README.md."
    out = Path(out_path)
    body = _marked_readme_section(Path(readme_path).read_text(encoding="utf-8"))
    text = f"{_skill_frontmatter(out)}\n\n{body}\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"Built {out} from {readme_path}")
    return cli_return(out)

# %% ../nbs/06_skill.ipynb #18227be1
@call_parse
@tracked_call
def install_nbskill(
    target: str = "codex",  # codex, claude, both, or custom when skills_dir is set
    skills_dir: str | None = None,  # Parent skills directory; skill is installed below jupyter-notebooks
    skill_name: str = "jupyter-notebooks",  # Skill folder name
    overwrite: bool = True,  # Overwrite an existing SKILL.md
):
    "Install the bundled SKILL.md into a Codex or Claude Code skills directory."
    target = target.lower()
    if skills_dir: roots = [Path(skills_dir).expanduser()]
    elif target == "codex": roots = [Path.home() / ".codex" / "skills"]
    elif target in {"claude", "claude-code", "claude_code"}: roots = [Path.home() / ".claude" / "skills"]
    elif target == "both": roots = [Path.home() / ".codex" / "skills", Path.home() / ".claude" / "skills"]
    else: raise ValueError("target must be codex, claude, both, or use skills_dir")
    package = files("nbskill")
    skill_text = package.joinpath("SKILL.md").read_text(encoding="utf-8")
    references = package.joinpath("references")
    installed = []
    for root in roots:
        dst_dir = root / skill_name
        dst = dst_dir / "SKILL.md"
        if dst.exists() and not overwrite: raise FileExistsError(dst)
        dst_dir.mkdir(parents=True, exist_ok=True)
        dst.write_text(skill_text, encoding="utf-8")
        if references.is_dir():
            ref_dir = dst_dir / "references"
            ref_dir.mkdir(exist_ok=True)
            for ref in references.iterdir():
                if ref.is_file():
                    (ref_dir / ref.name).write_text(ref.read_text(encoding="utf-8"), encoding="utf-8")
        installed.append(dst)
    msg = "\n".join(f"Installed {path}" for path in installed)
    print(msg)
    return cli_return(installed)
