"""Core notebook operations for coding agents.

`nbskill.skill` is the authoritative notebook workflow for an agent working with nbdev source. It supplies operations for preparing a change, editing cells, and proving the result.

Standalone instructions only route notebook-owned work here. Use it after aai-coding identifies the source; it does not replace the general coding workflow.

## Core workflow

For a nontrivial task, start with `prepare_change`: it combines compact source context with local prior art. Use `edit_notebook` for the one structured mutation, then `verify_change` to prove the code diff, focused execution, and changed-source diagnostics. Do not mutate raw `.ipynb` JSON or a generated module.

## Route source files

For a Python file, `generated_owner(path)` returns its notebook source or `None`. Use this Pyskill only for the returned notebook; every other file stays on the normal aai-coding path.

```python
summary = context("nbs/01_read.ipynb#context", scope="nbs", view="summary", verbose=False)
assert summary["kind"] == "context"
```

## Edit and review

Pass one small, explicit operation to `edit_notebook`. It validates and exports the notebook. `verify_change` runs only the affected scope without writing outputs, then returns the code diff and changed-source diagnostics.

```python
from nbskill.skill import *

prepare_change("nbs/02_edit.ipynb", "find the existing edit pattern")
edit_notebook("nbs/02_edit.ipynb", [edit])
proof = verify_change("nbs/02_edit.ipynb")
```

`verify_change` includes diagnostics only for changed source. It complements the behavior check and code-cell diff instead of replacing either.

Docs: https://MorsCerta-crypto.github.io/nbskill/pyskill.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_pyskill.ipynb.

# %% auto #0
__all__ = ['prepare_change', 'verify_change']

# %% ../nbs/14_pyskill.ipynb #a100cb81
import re

from .edit import edit_notebook
from .execute import exec_nb as _exec_nb
from .foundation import generated_owner
from .knowledge import reference_query as _reference_query
from .read import context
from .review import diff_nb as _diff_nb, style_report as _style_report

# %% ../nbs/14_pyskill.ipynb #76b38696
def _changed_execution_target(diff, up2id=None):
    "Choose an explicit execution target or the last changed code cell."
    if up2id is not None: return up2id
    changed = re.findall(r"^--- code cell (.+?) ---$", diff, flags=re.M)
    return changed[-1] if changed else None

# %% ../nbs/14_pyskill.ipynb #fe4c03fd
def prepare_change(
    path: str,  # Notebook path to inspect
    question: str,  # Implementation question for prior-art lookup
    scope: str = ".",  # Workspace used for context and local prior art
    top_k: int = 5,  # Number of prior-art hits to retain
    reference_path: str | None = None,  # Optional local reference index
):
    "Gather notebook context and local prior art before a change."
    return dict(
        context=context(path, scope=scope, view="summary", verbose=False),
        references=_reference_query(
            question, top_k=top_k, current_repo=scope, path=reference_path,
            include_local=True, allow_download=False,
        ),
    )

# %% ../nbs/14_pyskill.ipynb #6e6a4a71
def verify_change(
    path: str,  # Explicit affected notebook
    up2id: int | str | None = None,  # Optional focused execution target
    ref_a: str | None = "HEAD",  # First diff reference
    ref_b: str | None = None,  # Second diff reference
    timeout: int = 30,  # Per-cell execution timeout
    allow_new: bool = False,  # Permit unapproved cells in a disposable validation
):
    "Review a notebook diff, focused execution, and changed-source diagnostics."
    diff = _diff_nb(path, ref_a=ref_a, ref_b=ref_b)
    up2id = _changed_execution_target(diff, up2id)
    execution = _exec_nb(
        path, up2id=up2id, timeout=timeout, allow_new=allow_new,
        check_only=True, show_output=False,
    )
    diagnostics = _style_report(path, changed_only=True, ref_a=ref_a, ref_b=ref_b)
    return dict(path=str(path), up2id=up2id, diff=diff, execution=execution, diagnostics=diagnostics)

# %% ../nbs/14_pyskill.ipynb #b122e9dd
__all__ = ["context", "generated_owner", "prepare_change", "edit_notebook", "verify_change"]
