# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_write.ipynb.

# %% auto #0
__all__ = ['write_nb', 'update_cell', 'apply_nb']

# %% ../nbs/02_write.ipynb #04dbc0fe
import tomllib
from pathlib import Path

from fastcore.nbio import mk_cell, new_nb
from fastcore.nbio import read_nb as _read_nb
from fastcore.nbio import write_nb as _write_nb
from fastcore.script import Param, call_parse
from nbdev.doclinks import nbdev_export

from .execute import _run_notebook_test
from nbskill.foundation import (
    _cell_hash, _cell_matches_hash, _cell_source, _clear_outputs, _cli_error,
    _cli_return, _find_cell_by_id, _find_cell_by_text, _load_cells_text,
    _one_chapter, _parse_cells, _parse_one_cell, _replace_cell, _tracked_call,
    _validate_code_cells,
)

# %% ../nbs/02_write.ipynb #e14e4a46
@call_parse
@_tracked_call
def write_nb(
    path: str,  # Notebook path
    cells: Param("Cell block text", str, opt=False, nargs="?") = "",  # Cells to write; use - to read stdin
    cells_file: str | None = None,  # Read cell block text from a UTF-8 file to avoid shell escaping
    before_id: str | None = None,  # Insert before this stable cell id
    after_id: str | None = None,  # Insert after this stable cell id
    chapter: str | None = None,  # Chapter title string or regex; missing chapters are created
    replace: bool = False,  # Replace the full notebook, or the selected chapter body
    cell_type: str = "code",  # Default type for cells without %% marker
    export: bool = True,  # Run nbdev-export after writing
    run_test: bool = False,  # Execute the notebook with execnb after writing
    run_style: bool = False,  # Run chstyle after writing
    style_strict: bool = False,  # Fail when chstyle finds hints
    validate_code: bool = True,  # Validate new Python code cells before writing
):
    "Write cells to a notebook using append, replace, id anchors, or chapters."
    if before_id and after_id: _cli_error("Use either before_id or after_id, not both")
    if (before_id or after_id) and chapter is not None: _cli_error("Use id-based insertion or chapter insertion, not both")
    if (before_id or after_id) and replace: _cli_error("Use id-based insertion or replace, not both")
    path = Path(path)
    cells = _load_cells_text(cells, cells_file)
    new_cells = _parse_cells(cells, cell_type)
    if validate_code: _validate_code_cells(new_cells)

    if replace and chapter is None:
        nb = new_nb(new_cells)
    else:
        nb = _read_nb(path) if path.exists() else new_nb([])
        if chapter is not None:
            span = _one_chapter(nb.cells, chapter, create=True)
            if replace:
                del nb.cells[span["start"] + 1:span["end"]]
                target = span["start"] + 1
            else:
                target = span["end"]
        elif before_id or after_id:
            idx, _ = _find_cell_by_id(nb.cells, before_id or after_id)
            target = idx if before_id else idx + 1
        else:
            target = len(nb.cells)
        for offset, cell in enumerate(new_cells):
            nb.cells.insert(target + offset, cell)

    _write_nb(nb, path)
    if export: nbdev_export(path=str(path))
    msg = f"Wrote {len(nb.cells)} cells to {path}"
    if replace: msg += " using replace"
    if chapter is not None: msg += f" in chapter {chapter!r}"
    if before_id: msg += f" before id={before_id}"
    if after_id: msg += f" after id={after_id}"
    if export: msg += " and exported with nbdev"
    print(msg)
    if run_test: _run_notebook_test(path)
    if run_style:
        print(f"Running chstyle on {path}")
        _run_chstyle(path, strict=style_strict)
    return _cli_return(path)

# %% ../nbs/02_write.ipynb #5ef9f86f
def _save_nb(nb, path, export=True):
    _write_nb(nb, path)
    if export: nbdev_export(path=str(path))

# %% ../nbs/02_write.ipynb #8637ca42
@call_parse
@_tracked_call
def update_cell(
    path: str,  # Notebook path
    new: Param("Replacement cell source, or replacement text when old_str is set", str, opt=False, nargs="?") = "",
    new_file: str | None = None,  # Read replacement text from a UTF-8 file
    cell_id: str | None = None,  # Stable notebook cell id to update
    old_str: str | None = None,  # Text to replace, or text used to find the target cell
    source_hash: str | None = None,  # Expected current source SHA256 prefix
    cell_type: str = "code",  # Default type for whole-cell replacements without %% marker
    export: bool = True,  # Run nbdev-export after writing
    run_test: bool = False,  # Execute the notebook with execnb after writing
    validate_code: bool = True,  # Validate changed Python code before writing
    dry_run: bool = False,  # Show the update plan without writing
):
    "Update one notebook cell by id, or replace old_str inside one uniquely matching cell."
    if cell_id is None and old_str is None: _cli_error("Pass --cell_id, --old_str, or both")
    path = Path(path)
    nb = _read_nb(path)
    new = _load_cells_text(new, new_file)

    idx, cell = _find_cell_by_id(nb.cells, cell_id) if cell_id else _find_cell_by_text(nb.cells, old_str)
    if old_str is not None and old_str not in _cell_source(cell):
        _cli_error(f"old_str was not found in id={cell.id}")
    if not _cell_matches_hash(cell, source_hash):
        actual = _cell_hash(cell, n=None)
        _cli_error(f"Hash mismatch for id={cell.id}: expected {source_hash}, actual {actual[:12]}")

    before_hash = _cell_hash(cell)
    if old_str is None:
        new_cell = _parse_one_cell(new, cell_type)
        if validate_code: _validate_code_cells([new_cell])
        _clear_outputs(new_cell)
        if not dry_run: _replace_cell(nb, idx, new_cell)
        after_hash = _cell_hash(new_cell)
        mode = "cell"
    else:
        replacement = _cell_source(cell).replace(old_str, new, 1)
        if validate_code and getattr(cell, "cell_type", None) == "code": _validate_code_cells([mk_cell(replacement)])
        after_hash = _cell_hash(replacement)
        mode = "text"
        if not dry_run:
            cell.source = replacement
            _clear_outputs(cell)

    msg = f"{'Dry run: would update' if dry_run else 'Updated'} {mode} id={cell.id} hash={before_hash}->{after_hash}"
    if dry_run:
        print(msg)
        return _cli_return(path)
    _write_nb(nb, path)
    if export: nbdev_export(path=str(path))
    if export: msg += " and exported with nbdev"
    print(msg)
    if run_test: _run_notebook_test(path)
    return _cli_return(path)

# %% ../nbs/02_write.ipynb #ead02d6a
def _read_apply_nb_spec(spec_path):
    if spec_path == "-":
        import sys
        raw = sys.stdin.read()
        base = Path.cwd()
    else:
        path = Path(spec_path).expanduser()
        raw = path.read_text(encoding="utf-8")
        base = path.parent
    spec = tomllib.loads(raw)
    params = dict(spec.get("params", {}))
    for key, value in spec.items():
        if key != "params": params.setdefault(key, value)
    tool = params.pop("tool", params.pop("action", "write_nb"))
    cleanup = params.pop("cleanup", True)
    return tool, params, cleanup, base

# %% ../nbs/02_write.ipynb #22198dc5
def _resolve_sidecar_path(value, base):
    if value is None: return None
    path = Path(value).expanduser()
    return path if path.is_absolute() else base / path

# %% ../nbs/02_write.ipynb #4cdbb9a9
def _remove_if_sidecar(path, base):
    path = Path(path).expanduser()
    try:
        resolved, root = path.resolve(), Path(base).resolve()
        resolved.relative_to(root)
    except (OSError, ValueError):
        return False
    if resolved.exists() and resolved.is_file():
        resolved.unlink()
        return True
    return False

# %% ../nbs/02_write.ipynb #e57e560f
def _cleanup_apply_nb_inputs(spec_path, params, base, cleanup):
    if not cleanup or spec_path == "-": return []
    removed = []
    for key in ("cells_file", "new_file"):
        if params.get(key) and _remove_if_sidecar(_resolve_sidecar_path(params[key], base), base):
            removed.append(str(_resolve_sidecar_path(params[key], base)))
    if _remove_if_sidecar(spec_path, base): removed.append(str(Path(spec_path).expanduser()))
    return removed

# %% ../nbs/02_write.ipynb #6a9adfbb
@call_parse
@_tracked_call
def apply_nb(
    spec_path: Param("TOML operation file; use - to read TOML from stdin", str, opt=False, nargs="?") = "dev/nbskill-op.toml",
):
    "Apply a notebook operation from a TOML file and clean up dev sidecar files."
    tool, params, cleanup, base = _read_apply_nb_spec(spec_path)
    cleanup_params = dict(params)
    for key in ("cells_file", "new_file"):
        if params.get(key): params[key] = str(_resolve_sidecar_path(params[key], base))
    tools = {
        "write_nb": write_nb,
        "update_cell": update_cell,
    }
    if tool not in tools: _cli_error(f"Unknown apply_nb tool {tool!r}; expected one of {', '.join(tools)}")
    result = tools[tool](**params)
    removed = _cleanup_apply_nb_inputs(spec_path, cleanup_params, base, cleanup)
    if removed: print("Removed " + ", ".join(removed))
    return _cli_return(result)
