name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: uv sync --dev
      - run: uv run python -m compileall -q nbskill
      # - run: uv run nbskill_validate nbs
      - run: uv run nbdev-test --n_workers 0 --pause 1
      # - run: uv run style_check nbs --changed_only --max_diagnostics 80
